import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getSecurityContext } from "@/lib/security/activity";
import { createAdminClient } from "@/lib/supabase/admin";

const bodySchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("tag"), name: z.string().trim().min(1).max(50), color: z.string().trim().max(32).optional().nullable() }),
  z.object({ type: z.literal("deck"), name: z.string().trim().min(1).max(100), description: z.string().trim().max(1000).optional().nullable(), language: z.string().trim().max(20).optional().nullable() }),
  z.object({ type: z.literal("settings"), dailyNewGoal: z.number().int().min(0).max(200), dailyReviewGoal: z.number().int().min(1).max(500), flashcardPreferences: z.record(z.string(), z.unknown()).default({}) }),
]);
const deleteSchema = z.object({ type: z.enum(["tag", "deck"]), id: z.string().uuid() });

export async function POST(request: NextRequest) { const context = await getSecurityContext(); if (!context) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const parsed = bodySchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "請檢查設定內容。" }, { status: 400 }); try { const admin = createAdminClient(); if (parsed.data.type === "tag") { const { data, error } = await admin.from("vocabulary_tags").insert({ user_id: context.userId, name: parsed.data.name, color: parsed.data.color?.trim() || null }).select("id,name,color").single(); if (error) throw error; return NextResponse.json(data, { status: 201 }); } if (parsed.data.type === "deck") { const { data, error } = await admin.from("vocabulary_decks").insert({ user_id: context.userId, name: parsed.data.name, description: parsed.data.description?.trim() || null, language: parsed.data.language?.trim() || null }).select("id,name,description,language").single(); if (error) throw error; return NextResponse.json(data, { status: 201 }); } const { error } = await admin.from("vocabulary_settings").upsert({ user_id: context.userId, daily_new_goal: parsed.data.dailyNewGoal, daily_review_goal: parsed.data.dailyReviewGoal, flashcard_preferences: parsed.data.flashcardPreferences }); if (error) throw error; return NextResponse.json({ ok: true }); } catch { return NextResponse.json({ error: "無法儲存單字設定。" }, { status: 503 }); } }
export async function DELETE(request: NextRequest) { const context = await getSecurityContext(); if (!context) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const parsed = deleteSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "請選擇要刪除的項目。" }, { status: 400 }); try { const admin = createAdminClient(); const table = parsed.data.type === "tag" ? "vocabulary_tags" : "vocabulary_decks"; const { error } = await admin.from(table).delete().eq("id", parsed.data.id).eq("user_id", context.userId); if (error) throw error; return NextResponse.json({ ok: true }); } catch { return NextResponse.json({ error: "無法刪除項目。" }, { status: 503 }); } }
