"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { ModalDialog, OperationStatus } from "@/components/ui/modal-dialog";
import type { BahamutAnimeMatch } from "@/lib/anime/bahamut-anime-service";
import { animeStatusLabels, type AnimeLibraryItem, type AnimeStreamingPlatform, type AnimeTag, type AnimeWatchStatus, type AnimeWorkspaceData, type ExternalAnime } from "@/lib/anime/types";

type Tab = "library" | "search" | "stats";
const statuses: AnimeWatchStatus[] = ["watching", "planning", "completed", "paused", "dropped"];
const empty: AnimeWorkspaceData = { library: [], tags: [], logs: [], preferences: { preferredStreamingPlatform: "bahamut" } };
const keyOf = (a: ExternalAnime) => `${a.source}:${a.id}`;
const date = (value: string | null) => value ? new Intl.DateTimeFormat("zh-TW", { month: "short", day: "numeric" }).format(new Date(value)) : "尚未觀看";
const pct = (a: AnimeLibraryItem) => a.episodes ? Math.min(100, Math.round(a.watchedEpisodes / a.episodes * 100)) : 0;
async function api<T>(url: string, init?: RequestInit) { const r = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } }); const body = await r.json().catch(() => ({})); if (!r.ok) throw new Error(typeof body.error === "string" ? body.error : "操作失敗，請稍後再試。"); return body as T; }
function Cover({ anime, className = "anime-cover" }: { anime: Pick<AnimeLibraryItem | ExternalAnime, "coverUrl" | "title">; className?: string }) { return anime.coverUrl ? <img alt={`${anime.title} 封面`} className={className} loading="lazy" src={anime.coverUrl} /> : <div className={`${className} anime-cover-fallback`}>ANIME</div>; }
function Status({ value }: { value: AnimeWatchStatus }) { return <span className={`anime-status status-${value}`}>{animeStatusLabels[value]}</span>; }

export function AnimeWorkspace({ initialData }: { initialData: AnimeWorkspaceData }) {
  const [data, setData] = useState(initialData ?? empty); const [tab, setTab] = useState<Tab>("library"); const [filter, setFilter] = useState<"all" | "favorite" | AnimeWatchStatus>("all"); const [query, setQuery] = useState(""); const [results, setResults] = useState<ExternalAnime[]>([]); const [loading, setLoading] = useState(false); const [searchError, setSearchError] = useState<string | null>(null); const [pending, setPending] = useState<string | null>(null); const [selected, setSelected] = useState<AnimeLibraryItem | null>(null); const [adding, setAdding] = useState<ExternalAnime | null>(null); const [removing, setRemoving] = useState<AnimeLibraryItem | null>(null); const [notice, setNotice] = useState<string | null>(null); const [bahamut, setBahamut] = useState<Record<string, BahamutAnimeMatch | null>>({});
  const cache = useRef(new Map<string, { until: number; rows: ExternalAnime[] }>()); const checking = useRef(new Set<string>());
  const library = useMemo(() => data.library.filter((a) => (filter === "all" ? true : filter === "favorite" ? a.favorite : a.watchStatus === filter) && [a.title, a.titleJapanese, a.titleEnglish, a.notes, ...a.tags.map((t) => t.name)].filter(Boolean).join(" ").toLocaleLowerCase().includes(query.toLocaleLowerCase())), [data.library, filter, query]);
  const existing = useMemo(() => new Set(data.library.map((a) => `${a.externalSource}:${a.externalId}`)), [data.library]);
  const refresh = async () => { setPending("refresh"); try { setData(await api<AnimeWorkspaceData>("/api/anime/library")); } catch (e) { setNotice(e instanceof Error ? e.message : "無法更新動漫資料。"); } finally { setPending(null); } };
  useEffect(() => { const text = query.trim(); if (tab !== "search" || text.length < 2) { setLoading(false); setSearchError(null); return; } const cacheKey = text.normalize("NFKC").toLocaleLowerCase(); const hit = cache.current.get(cacheKey); if (hit && hit.until > Date.now()) { setResults(hit.rows); setLoading(false); setSearchError(null); return; } const controller = new AbortController(); const timer = window.setTimeout(async () => { setLoading(true); setSearchError(null); try { const answer = await api<{ results: ExternalAnime[] }>(`/api/anime/search?q=${encodeURIComponent(text)}`, { signal: controller.signal }); if (!controller.signal.aborted) { setResults(answer.results); cache.current.set(cacheKey, { until: Date.now() + 20 * 60 * 1_000, rows: answer.results }); } } catch (e) { if (!controller.signal.aborted) setSearchError(!navigator.onLine ? "目前沒有網路連線" : e instanceof Error ? e.message : "搜尋失敗，請稍後再試"); } finally { if (!controller.signal.aborted) setLoading(false); } }, 700); return () => { controller.abort(); window.clearTimeout(timer); }; }, [query, tab]);
  useEffect(() => { if (tab !== "search") return; const controller = new AbortController(); const queue = results.filter((a) => !checking.current.has(keyOf(a))); queue.forEach((a) => checking.current.add(keyOf(a))); void (async () => { for (const anime of queue) { if (controller.signal.aborted) return; const p = new URLSearchParams({ title: anime.title }); if (anime.titleJapanese) p.set("japanese", anime.titleJapanese); if (anime.titleEnglish) p.set("english", anime.titleEnglish); if (anime.titleChinese) p.set("chinese", anime.titleChinese); try { const answer = await api<{ match: BahamutAnimeMatch }>(`/api/anime/bahamut?${p}`, { signal: controller.signal }); if (!controller.signal.aborted) setBahamut((v) => ({ ...v, [keyOf(anime)]: answer.match })); } catch { if (!controller.signal.aborted) setBahamut((v) => ({ ...v, [keyOf(anime)]: null })); } } })(); return () => controller.abort(); }, [results, tab]);
  const setPreference = async (preferredStreamingPlatform: AnimeStreamingPlatform) => { setPending("preference"); try { await api("/api/anime/preferences", { method: "PATCH", body: JSON.stringify({ preferredStreamingPlatform }) }); setData((v) => ({ ...v, preferences: { preferredStreamingPlatform } })); } catch (e) { setNotice(e instanceof Error ? e.message : "無法儲存串流平台偏好。"); } finally { setPending(null); } };
  const alterProgress = async (anime: AnimeLibraryItem, action: "increment" | "decrement") => { setPending(`progress-${anime.id}`); try { await api(`/api/anime/library/${anime.id}/progress`, { method: "POST", body: JSON.stringify({ action }) }); await refresh(); } catch (e) { setNotice(e instanceof Error ? e.message : "無法更新進度。"); } finally { setPending(null); } };
  const remove = async () => { if (!removing) return; setPending("remove"); try { await api("/api/anime/library", { method: "DELETE", body: JSON.stringify({ id: removing.id }) }); setSelected(null); setRemoving(null); await refresh(); } catch (e) { setNotice(e instanceof Error ? e.message : "無法移除動漫。"); } finally { setPending(null); } };
  return <section className="anime-workspace">
    {pending && <OperationStatus label={pending === "refresh" ? "正在同步動漫資料…" : "正在儲存動漫資料…"} />}
    <div className="anime-toolbar"><div className="anime-tabs" role="tablist" aria-label="動漫功能"><button className={tab === "library" ? "active" : ""} onClick={() => setTab("library")} type="button">我的動漫</button><button className={tab === "search" ? "active" : ""} onClick={() => setTab("search")} type="button">搜尋動漫</button><button className={tab === "stats" ? "active" : ""} onClick={() => setTab("stats")} type="button">統計</button></div>{tab !== "search" && <button className="button compact" onClick={() => setTab("search")} type="button">＋ 搜尋並加入</button>}</div>
    {notice && <div className="notice success anime-notice"><span>{notice}</span><button aria-label="關閉提示" onClick={() => setNotice(null)} type="button">×</button></div>}
    {tab === "library" && <><div className="anime-library-intro"><div><p className="eyebrow">PERSONAL ANIME LIBRARY</p><h2>繼續觀看</h2><p>作品資料與觀看紀錄保存在你的私人收藏庫。</p></div><div className="anime-library-preferences"><label>偏好串流平台<select disabled={Boolean(pending)} onChange={(e) => void setPreference(e.target.value as AnimeStreamingPlatform)} value={data.preferences.preferredStreamingPlatform}><option value="bahamut">動畫瘋</option><option value="netflix">Netflix</option><option value="crunchyroll">Crunchyroll</option><option value="other">其他</option></select></label><div className="anime-mini-stats"><strong>{data.library.filter((a) => a.watchStatus === "watching").length}</strong><span>正在觀看</span></div></div></div><div className="anime-filter-bar"><div className="anime-filter-scroll">{(["all", ...statuses, "favorite"] as const).map((v) => <button className={filter === v ? "active" : ""} key={v} onClick={() => setFilter(v)} type="button">{v === "all" ? "全部" : v === "favorite" ? "收藏" : animeStatusLabels[v]}</button>)}</div><input aria-label="搜尋自己的動漫" onChange={(e) => setQuery(e.target.value)} placeholder="搜尋名稱、標籤或備註" value={query} /></div><div className="anime-grid">{library.map((a) => <article className="anime-card" key={a.id}><button className="anime-card-main" onClick={() => setSelected(a)} type="button"><Cover anime={a} /><div className="anime-card-copy"><div className="anime-card-line"><Status value={a.watchStatus} />{a.favorite && <span className="anime-favorite">♥</span>}</div><h3>{a.title}</h3><p>{a.titleJapanese || a.titleEnglish || a.animeType || "Anime"}</p><div className="anime-progress"><span>{a.watchedEpisodes} / {a.episodes ?? "?"} 集</span><i><b style={{ width: `${pct(a)}%` }} /></i></div></div></button>{a.watchStatus === "watching" && <div className="anime-quick-progress"><button disabled={a.watchedEpisodes === 0 || Boolean(pending)} onClick={() => void alterProgress(a, "decrement")} type="button">−</button><strong>{a.watchedEpisodes}</strong><button disabled={Boolean(pending)} onClick={() => void alterProgress(a, "increment")} type="button">＋1</button></div>}</article>)}</div>{library.length === 0 && <div className="anime-empty"><h3>{data.library.length ? "找不到符合的動漫" : "還沒有加入動漫"}</h3><button className="button compact" onClick={() => setTab("search")} type="button">搜尋動漫</button></div>}</>}
    {tab === "search" && <><div className="anime-search-heading"><p className="eyebrow">ANIME DATABASE</p><h2>搜尋動漫</h2><p>外部動漫資料與動畫瘋官方上架資訊會分開確認。</p></div><label className="anime-search-box"><i>⌕</i><input autoFocus onChange={(e) => setQuery(e.target.value)} placeholder="例如：進擊的巨人、Frieren、進撃の巨人" value={query} /></label>{loading && <div className="anime-search-state">正在搜尋 Anime Database…</div>}{searchError && <div className="notice error">{searchError}</div>}<div className="anime-search-grid">{query.trim().length >= 2 && results.map((a) => { const match = bahamut[keyOf(a)]; return <article className="anime-search-card" key={keyOf(a)}><Cover anime={a} className="anime-search-cover" /><div><p className="anime-result-type">{a.animeType ?? "Anime"} {a.releaseYear ? `· ${a.releaseYear}` : ""}</p><h3>{a.title}</h3><p>{a.titleJapanese || a.titleEnglish || "未提供其他名稱"}</p><small>{a.episodes ? `${a.episodes} 集` : "集數未定"}</small>{match?.available && <small className="bahamut-available">動畫瘋 ✓</small>}{match?.available === false && <small>動畫瘋目前未找到</small>}<div className="anime-result-actions"><button className="secondary-button" onClick={() => setAdding(a)} type="button">{existing.has(keyOf(a)) ? "查看／更新" : "＋ 加入我的動漫"}</button></div></div></article>; })}</div>{!loading && query.trim().length >= 2 && !searchError && results.length === 0 && <div className="anime-empty"><h3>找不到相關動漫</h3><p>試試不同名稱、羅馬拼音或日文名稱。</p></div>}</>}
    {tab === "stats" && <AnimeStats data={data} />}
    {adding && <AddDialog anime={adding} bahamut={bahamut[keyOf(adding)]} existing={data.library.find((a) => a.externalId === adding.id && a.externalSource === adding.source) ?? null} onClose={() => setAdding(null)} onSaved={async () => { setAdding(null); await refresh(); setTab("library"); }} tags={data.tags} />}
    {selected && <DetailDialog anime={selected} preferred={data.preferences.preferredStreamingPlatform} onClose={() => setSelected(null)} onRemove={() => setRemoving(selected)} onSaved={async () => { await refresh(); setSelected(null); }} tags={data.tags} />}
    <ConfirmDialog confirmLabel="移至垃圾桶" description={removing ? `確定要將《${removing.title}》移至垃圾桶嗎？` : ""} onCancel={() => setRemoving(null)} onConfirm={() => void remove()} open={Boolean(removing)} pending={pending === "remove"} title="移除我的動漫" />
  </section>;
}
function AnimeStats({ data }: { data: AnimeWorkspaceData }) { const watched = data.library.reduce((n, a) => n + a.watchedEpisodes, 0); return <><div className="anime-stats-grid"><article><small>總收藏</small><strong>{data.library.length}</strong><span>部動漫</span></article><article><small>已觀看集數</small><strong>{watched}</strong><span>集</span></article><article><small>正在觀看</small><strong>{data.library.filter((a) => a.watchStatus === "watching").length}</strong><span>部</span></article><article><small>平均評分</small><strong>—</strong><span>/ 10</span></article></div><section className="anime-history"><h2>最近觀看</h2>{data.logs.slice(0, 8).map((log) => <div key={log.id}><span>{date(log.watchedAt)}</span><strong>{data.library.find((a) => a.id === log.animeId)?.title ?? "已移除的動漫"}</strong><small>第 {log.fromEpisode} 集 → 第 {log.toEpisode} 集</small></div>)}</section></>; }
function AddDialog({ anime, bahamut, existing, tags, onClose, onSaved }: { anime: ExternalAnime; bahamut: BahamutAnimeMatch | null | undefined; existing: AnimeLibraryItem | null; tags: AnimeTag[]; onClose: () => void; onSaved: () => Promise<void> }) { const [watchStatus, setWatchStatus] = useState<AnimeWatchStatus>(existing?.watchStatus ?? "planning"); const [watchedEpisodes, setEpisodes] = useState(existing?.watchedEpisodes ?? 0); const [favorite, setFavorite] = useState(existing?.favorite ?? false); const [tagIds, setTagIds] = useState(existing?.tags.map((t) => t.id) ?? []); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null); const save = async () => { setPending(true); try { await api("/api/anime/library", { method: "POST", body: JSON.stringify({ externalId: anime.id, externalSource: anime.source, watchStatus, watchedEpisodes, favorite, tagIds }) }); await onSaved(); } catch (e) { setMessage(e instanceof Error ? e.message : "無法加入動漫。"); } finally { setPending(false); } }; return <ModalDialog onClose={onClose} open pending={pending} title={existing ? "更新我的動漫" : "加入我的動漫"}><div className="anime-dialog"><div className="anime-dialog-title"><Cover anime={anime} /><div><Status value={watchStatus} /><h3>{anime.title}</h3><p>{anime.titleJapanese || anime.titleEnglish}</p></div></div><div className="anime-streaming-inline">{bahamut?.available ? "動畫瘋 ✓ 已找到官方作品頁" : bahamut?.available === false ? "動畫瘋目前未找到；儲存時仍會再確認一次。" : "正在確認動畫瘋上架資訊…"}</div><label>觀看狀態<select onChange={(e) => setWatchStatus(e.target.value as AnimeWatchStatus)} value={watchStatus}>{statuses.map((s) => <option key={s} value={s}>{animeStatusLabels[s]}</option>)}</select></label><label>目前看到第幾集<input max={anime.episodes ?? undefined} min="0" onChange={(e) => setEpisodes(Math.max(0, Number(e.target.value) || 0))} type="number" value={watchedEpisodes} /></label><label className="anime-check"><input checked={favorite} onChange={(e) => setFavorite(e.target.checked)} type="checkbox" /> 加入我的收藏</label><fieldset><legend>自訂標籤</legend><div className="anime-tag-picker">{tags.map((t) => <label key={t.id}><input checked={tagIds.includes(t.id)} onChange={() => setTagIds((ids) => ids.includes(t.id) ? ids.filter((id) => id !== t.id) : [...ids, t.id])} type="checkbox" /> {t.name}</label>)}</div></fieldset>{message && <p className="notice error">{message}</p>}<div className="dialog-actions"><button className="button" disabled={pending} onClick={() => void save()} type="button">{pending ? "儲存中…" : "加入我的動漫"}</button><button className="secondary-button" disabled={pending} onClick={onClose} type="button">取消</button></div></div></ModalDialog>; }
function DetailDialog({ anime, preferred, tags, onClose, onSaved, onRemove }: { anime: AnimeLibraryItem; preferred: AnimeStreamingPlatform; tags: AnimeTag[]; onClose: () => void; onSaved: () => void; onRemove: () => void }) { const [watchStatus, setWatchStatus] = useState<AnimeWatchStatus>(anime.watchStatus); const [rating, setRating] = useState(anime.rating?.toString() ?? ""); const [notes, setNotes] = useState(anime.notes ?? ""); const [favorite, setFavorite] = useState(anime.favorite); const [tagIds, setTagIds] = useState(anime.tags.map((t) => t.id)); const [pending, setPending] = useState(false); const save = async () => { setPending(true); try { await api("/api/anime/library", { method: "PATCH", body: JSON.stringify({ id: anime.id, watchStatus, rating: rating === "" ? null : Number(rating), notes, favorite, tagIds }) }); await onSaved(); } finally { setPending(false); } }; return <ModalDialog onClose={onClose} open pending={pending} title="動漫詳細資訊"><div className="anime-detail"><div className="anime-detail-hero">{anime.bannerUrl && <img alt="" src={anime.bannerUrl} />}<div><Cover anime={anime} /><div><Status value={anime.watchStatus} /><h3>{anime.title}</h3><p>{anime.titleJapanese || anime.titleEnglish || anime.originalTitle}</p></div></div></div><section className="anime-streaming"><h4>串流平台</h4>{anime.bahamutAvailable ? <><p><strong>動畫瘋 ✓</strong>{anime.bahamutTitle ? ` ${anime.bahamutTitle}` : ""}</p><a className="button compact" href={anime.bahamutUrl ?? undefined} rel="noreferrer" target="_blank">{preferred === "bahamut" ? "▶ 繼續觀看" : "前往動畫瘋觀看"}</a></> : anime.bahamutAvailable === false ? <p>動畫瘋目前未找到</p> : <p>動畫瘋上架資訊尚未確認。</p>}</section>{anime.synopsis && <section><h4>劇情介紹</h4><p>{anime.synopsis}</p></section>}<div className="anime-edit-grid"><label>觀看狀態<select onChange={(e) => setWatchStatus(e.target.value as AnimeWatchStatus)} value={watchStatus}>{statuses.map((s) => <option key={s} value={s}>{animeStatusLabels[s]}</option>)}</select></label><label>我的評分（0–10）<input max="10" min="0" onChange={(e) => setRating(e.target.value)} step="0.5" type="number" value={rating} /></label></div><label className="anime-check"><input checked={favorite} onChange={(e) => setFavorite(e.target.checked)} type="checkbox" /> 收藏這部動漫</label><fieldset><legend>我的標籤</legend><div className="anime-tag-picker">{tags.map((t) => <label key={t.id}><input checked={tagIds.includes(t.id)} onChange={() => setTagIds((ids) => ids.includes(t.id) ? ids.filter((id) => id !== t.id) : [...ids, t.id])} type="checkbox" /> {t.name}</label>)}</div></fieldset><label>私人備註<textarea onChange={(e) => setNotes(e.target.value)} rows={4} value={notes} /></label><div className="dialog-actions anime-detail-actions"><button className="button" disabled={pending} onClick={() => void save()} type="button">{pending ? "儲存中…" : "儲存修改"}</button><button className="secondary-button" disabled={pending} onClick={onRemove} type="button">移至垃圾桶</button></div></div></ModalDialog>; }
