"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { ModalDialog, OperationStatus } from "@/components/ui/modal-dialog";
import { animeStatusLabels, type AnimeLibraryItem, type AnimeTag, type AnimeWatchStatus, type AnimeWorkspaceData, type ExternalAnime } from "@/lib/anime/types";

type Tab = "library" | "search" | "stats";
const statusOrder: AnimeWatchStatus[] = ["watching", "planning", "completed", "paused", "dropped"];
const emptyData: AnimeWorkspaceData = { library: [], tags: [], logs: [] };
const searchDebounceMs = 700;
const searchCacheTtlMs = 20 * 60 * 1_000;
const progress = (anime: Pick<AnimeLibraryItem, "episodes" | "watchedEpisodes">) => anime.episodes ? Math.min(100, Math.round((anime.watchedEpisodes / anime.episodes) * 100)) : 0;
const day = (value: string | null) => value ? new Intl.DateTimeFormat("zh-TW", { month: "short", day: "numeric" }).format(new Date(value)) : "尚未觀看";

async function request<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "操作失敗，請稍後再試。");
  return data as T;
}

function Cover({ anime, className = "anime-cover" }: { anime: Pick<AnimeLibraryItem | ExternalAnime, "coverUrl" | "title">; className?: string }) {
  return anime.coverUrl ? <img alt={`${anime.title} 封面`} className={className} loading="lazy" src={anime.coverUrl} /> : <div aria-label={`${anime.title} 預設封面`} className={`${className} anime-cover-fallback`}>ANIME</div>;
}

function StatusPill({ status }: { status: AnimeWatchStatus }) { return <span className={`anime-status status-${status}`}>{animeStatusLabels[status]}</span>; }

export function AnimeWorkspace({ initialData }: { initialData: AnimeWorkspaceData }) {
  const [data, setData] = useState(initialData ?? emptyData); const [tab, setTab] = useState<Tab>("library"); const [filter, setFilter] = useState<"all" | AnimeWatchStatus | "favorite">("all"); const [query, setQuery] = useState(""); const [results, setResults] = useState<ExternalAnime[]>([]); const [searchLoading, setSearchLoading] = useState(false); const [searchError, setSearchError] = useState<string | null>(null); const [pending, setPending] = useState<string | null>(null); const [selected, setSelected] = useState<AnimeLibraryItem | null>(null); const [adding, setAdding] = useState<ExternalAnime | null>(null); const [removing, setRemoving] = useState<AnimeLibraryItem | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const searchCache = useRef(new Map<string, { expiresAt: number; results: ExternalAnime[] }>());
  const existingIds = useMemo(() => new Set(data.library.map((anime) => `${anime.externalSource}:${anime.externalId}`)), [data.library]);
  const library = useMemo(() => data.library.filter((anime) => (filter === "all" ? true : filter === "favorite" ? anime.favorite : anime.watchStatus === filter) && [anime.title, anime.titleJapanese, anime.titleEnglish, anime.notes, ...anime.tags.map((tag) => tag.name)].filter(Boolean).join(" ").toLocaleLowerCase().includes(query.toLocaleLowerCase())), [data.library, filter, query]);
  const stats = useMemo(() => ({ total: data.library.length, episodes: data.library.reduce((sum, anime) => sum + anime.watchedEpisodes, 0), minutes: data.library.reduce((sum, anime) => sum + anime.watchedEpisodes * (anime.episodeDuration ?? 0), 0), score: data.library.filter((anime) => anime.rating !== null).reduce((sum, anime, _index, rows) => sum + (anime.rating ?? 0) / rows.length, 0) }), [data.library]);
  const refresh = async () => { setPending("refresh"); try { setData(await request<AnimeWorkspaceData>("/api/anime/library")); } catch (caught) { setNotice(caught instanceof Error ? caught.message : "無法更新動漫資料。"); } finally { setPending(null); } };
  useEffect(() => {
    const normalizedQuery = query.trim();
    if (tab !== "search" || normalizedQuery.length < 2) { setSearchLoading(false); setSearchError(null); return; }
    const cacheKey = normalizedQuery.normalize("NFKC").toLocaleLowerCase();
    const cached = searchCache.current.get(cacheKey);
    if (cached && cached.expiresAt > Date.now()) { setResults(cached.results); setSearchLoading(false); setSearchError(null); return; }
    if (cached) searchCache.current.delete(cacheKey);
    const controller = new AbortController();
    const timer = window.setTimeout(async () => {
      setSearchLoading(true); setSearchError(null);
      try {
        const answer = await request<{ results: ExternalAnime[] }>(`/api/anime/search?q=${encodeURIComponent(normalizedQuery)}`, { signal: controller.signal });
        if (controller.signal.aborted) return;
        setResults(answer.results);
        searchCache.current.set(cacheKey, { expiresAt: Date.now() + searchCacheTtlMs, results: answer.results });
      } catch (caught) {
        if (!controller.signal.aborted) {
          const offline = typeof navigator !== "undefined" && !navigator.onLine;
          setSearchError(offline ? "目前沒有網路連線" : caught instanceof Error ? caught.message : "搜尋失敗，請稍後再試");
        }
      } finally { if (!controller.signal.aborted) setSearchLoading(false); }
    }, searchDebounceMs);
    return () => { controller.abort(); window.clearTimeout(timer); };
  }, [query, tab]);
  async function changeProgress(anime: AnimeLibraryItem, action: "increment" | "decrement") { setPending(`progress-${anime.id}`); try { const answer = await request<{ shouldComplete: boolean }>(`/api/anime/library/${anime.id}/progress`, { method: "POST", body: JSON.stringify({ action }) }); await refresh(); if (answer.shouldComplete) { setSelected(data.library.find((item) => item.id === anime.id) ?? anime); setNotice("已達到最後一集；可在詳細資訊將狀態標記為「已看完」。"); } } catch (caught) { setNotice(caught instanceof Error ? caught.message : "無法更新進度。"); } finally { setPending(null); } }
  async function removeAnime() { if (!removing) return; setPending("remove"); try { await request("/api/anime/library", { method: "DELETE", body: JSON.stringify({ id: removing.id }) }); setSelected(null); setRemoving(null); await refresh(); } catch (caught) { setNotice(caught instanceof Error ? caught.message : "無法移除動漫。"); } finally { setPending(null); } }
  return <section className="anime-workspace">
    {pending && <OperationStatus label={pending === "refresh" ? "正在同步動漫資料…" : "正在儲存動漫資料…"} />}
    <div className="anime-toolbar"><div className="anime-tabs" role="tablist" aria-label="動漫功能"><button aria-selected={tab === "library"} className={tab === "library" ? "active" : ""} onClick={() => setTab("library")} role="tab" type="button">我的動漫</button><button aria-selected={tab === "search"} className={tab === "search" ? "active" : ""} onClick={() => setTab("search")} role="tab" type="button">搜尋動漫</button><button aria-selected={tab === "stats"} className={tab === "stats" ? "active" : ""} onClick={() => setTab("stats")} role="tab" type="button">統計</button></div>{tab !== "search" && <button className="button compact" onClick={() => setTab("search")} type="button">＋ 搜尋並加入</button>}</div>
    {notice && <div className="notice success anime-notice"><span>{notice}</span><button aria-label="關閉提示" onClick={() => setNotice(null)} type="button">×</button></div>}
    {tab === "library" && <><div className="anime-library-intro"><div><p className="eyebrow">PERSONAL ANIME LIBRARY</p><h2>繼續觀看</h2><p>更新一集只要按一下；作品資料會安全保存在你的私人收藏庫。</p></div><div className="anime-mini-stats"><strong>{data.library.filter((anime) => anime.watchStatus === "watching").length}</strong><span>正在觀看</span></div></div><div className="anime-filter-bar"><div className="anime-filter-scroll">{(["all", ...statusOrder, "favorite"] as const).map((value) => <button className={filter === value ? "active" : ""} key={value} onClick={() => setFilter(value)} type="button">{value === "all" ? "全部" : value === "favorite" ? "收藏" : animeStatusLabels[value]} <small>{value === "all" ? data.library.length : value === "favorite" ? data.library.filter((anime) => anime.favorite).length : data.library.filter((anime) => anime.watchStatus === value).length}</small></button>)}</div><label className="sr-only" htmlFor="anime-library-search">搜尋自己的動漫</label><input id="anime-library-search" onChange={(event) => setQuery(event.target.value)} placeholder="搜尋名稱、標籤或備註" value={query} /></div><div className="anime-grid">{library.map((anime) => <article className="anime-card" key={anime.id}><button aria-label={`查看 ${anime.title} 詳細資訊`} className="anime-card-main" onClick={() => setSelected(anime)} type="button"><Cover anime={anime} /><div className="anime-card-copy"><div className="anime-card-line"><StatusPill status={anime.watchStatus} />{anime.favorite && <span aria-label="收藏" className="anime-favorite">♥</span>}</div><h3>{anime.title}</h3><p>{anime.titleJapanese || anime.titleEnglish || anime.animeType || "Anime"}</p><div className="anime-progress"><span>{anime.watchedEpisodes} / {anime.episodes ?? "?"} 集</span><i><b style={{ width: `${progress(anime)}%` }} /></i></div>{anime.rating !== null && <small>我的評分 {anime.rating.toFixed(1)} / 10</small>}</div></button>{anime.watchStatus === "watching" && <div className="anime-quick-progress"><button aria-label={`減少 ${anime.title} 一集`} disabled={anime.watchedEpisodes === 0 || Boolean(pending)} onClick={() => void changeProgress(anime, "decrement")} type="button">−</button><strong>{anime.watchedEpisodes}</strong><button aria-label={`看完 ${anime.title} 一集`} disabled={anime.episodes !== null && anime.watchedEpisodes >= anime.episodes || Boolean(pending)} onClick={() => void changeProgress(anime, "increment")} type="button">＋1</button></div>}</article>)}</div>{library.length === 0 && <div className="anime-empty"><span>◉</span><h3>{data.library.length ? "找不到符合的動漫" : "還沒有加入動漫"}</h3><p>{data.library.length ? "試著改變狀態或搜尋條件。" : "從 Anime Database 搜尋作品後，一鍵加入自己的收藏庫。"}</p><button className="button compact" onClick={() => setTab("search")} type="button">搜尋動漫</button></div>}</>}
    {tab === "search" && <><div className="anime-search-heading"><p className="eyebrow">ANIME DATABASE</p><h2>搜尋動漫</h2><p>輸入中文、日文或英文名稱，資料由外部 Anime Database 取得；加入後會快取在你的私人收藏庫。</p></div><label className="anime-search-box"><span className="sr-only">搜尋動漫</span><i>⌕</i><input autoFocus onChange={(event) => setQuery(event.target.value)} placeholder="例如：進擊的巨人、Frieren、進撃の巨人" value={query} /></label>{searchLoading && <div className="anime-search-state">正在搜尋 Anime Database…</div>}{searchError && <div className="notice error">{searchError}</div>}<div className="anime-search-grid">{(query.trim().length >= 2 ? results : []).map((anime) => <article className="anime-search-card" key={`${anime.source}:${anime.id}`}><Cover anime={anime} className="anime-search-cover" /><div><p className="anime-result-type">{anime.animeType ?? "Anime"} {anime.releaseYear ? `· ${anime.releaseYear}` : ""}</p><h3>{anime.title}</h3><p>{anime.titleJapanese || anime.titleEnglish || "未提供其他名稱"}</p><small>{anime.episodes ? `${anime.episodes} 集` : "集數未定"} · {anime.broadcastStatus ?? "播出資訊未提供"}</small><div className="anime-result-actions"><button className="secondary-button" onClick={() => setAdding(anime)} type="button">{existingIds.has(`${anime.source}:${anime.id}`) ? "查看／更新" : "＋ 加入我的動漫"}</button></div></div></article>)}</div>{!searchLoading && query.trim().length >= 2 && !searchError && results.length === 0 && <div className="anime-empty"><h3>找不到相關動漫</h3><p>試試不同名稱、羅馬拼音或日文名稱。</p></div>}</>}
    {tab === "stats" && <><div className="anime-stats-grid"><article><small>總收藏</small><strong>{stats.total}</strong><span>部動漫</span></article><article><small>已觀看集數</small><strong>{stats.episodes}</strong><span>集</span></article><article><small>估算觀看時間</small><strong>{Math.round(stats.minutes / 60)}</strong><span>小時</span></article><article><small>平均評分</small><strong>{stats.score ? stats.score.toFixed(1) : "—"}</strong><span>/ 10</span></article></div><section className="anime-status-summary"><h2>觀看狀態</h2>{statusOrder.map((status) => <div key={status}><span><StatusPill status={status} />{animeStatusLabels[status]}</span><strong>{data.library.filter((anime) => anime.watchStatus === status).length} 部</strong></div>)}</section><section className="anime-history"><h2>最近觀看</h2>{data.logs.slice(0, 8).map((log) => { const anime = data.library.find((item) => item.id === log.animeId); return <div key={log.id}><span>{day(log.watchedAt)}</span><strong>{anime?.title ?? "已移除的動漫"}</strong><small>第 {log.fromEpisode} 集 → 第 {log.toEpisode} 集</small></div>; })}{data.logs.length === 0 && <p>更新觀看進度後，這裡會顯示你的觀看歷史。</p>}</section></>}
    {selected && <AnimeDetailDialog anime={selected} onClose={() => setSelected(null)} onRemove={() => setRemoving(selected)} onSaved={async () => { await refresh(); setSelected(null); }} tags={data.tags} />}
    {adding && <AddAnimeDialog anime={adding} existing={data.library.find((item) => item.externalId === adding.id && item.externalSource === adding.source) ?? null} onClose={() => setAdding(null)} onSaved={async () => { setAdding(null); await refresh(); setTab("library"); }} tags={data.tags} />}
    <ConfirmDialog confirmLabel="移至垃圾桶" description={removing ? `確定要將《${removing.title}》移至垃圾桶嗎？你的觀看歷史會保留，之後仍可復原。` : ""} onCancel={() => setRemoving(null)} onConfirm={() => void removeAnime()} open={Boolean(removing)} pending={pending === "remove"} title="移除我的動漫" />
  </section>;
}

function AddAnimeDialog({ anime, existing, tags, onClose, onSaved }: { anime: ExternalAnime; existing: AnimeLibraryItem | null; tags: AnimeTag[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [watchStatus, setWatchStatus] = useState<AnimeWatchStatus>(existing?.watchStatus ?? "planning"); const [watchedEpisodes, setWatchedEpisodes] = useState(existing?.watchedEpisodes ?? 0); const [selectedTags, setSelectedTags] = useState<string[]>(existing?.tags.map((tag) => tag.id) ?? []); const [favorite, setFavorite] = useState(existing?.favorite ?? false); const [tagName, setTagName] = useState(""); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const submit = async () => { setPending(true); setMessage(null); try { let tagIds = selectedTags; if (tagName.trim()) { const response = await request<{ tag: AnimeTag }>("/api/anime/tags", { method: "POST", body: JSON.stringify({ name: tagName.trim(), color: "#2d67c7" }) }); tagIds = [...selectedTags, response.tag.id]; setSelectedTags(tagIds); } await request("/api/anime/library", { method: "POST", body: JSON.stringify({ externalId: anime.id, externalSource: anime.source, watchStatus, watchedEpisodes, favorite, tagIds }) }); await onSaved(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "無法加入動漫。"); } finally { setPending(false); } };
  return <ModalDialog onClose={onClose} open={Boolean(anime)} pending={pending} title={existing ? "更新我的動漫" : "加入我的動漫"}>{anime && <div className="anime-dialog"><div className="anime-dialog-title"><Cover anime={anime} /><div><StatusPill status={watchStatus} /><h3>{anime.title}</h3><p>{anime.titleJapanese || anime.titleEnglish || anime.animeType}</p></div></div><label>觀看狀態<select onChange={(event) => setWatchStatus(event.target.value as AnimeWatchStatus)} value={watchStatus}>{statusOrder.map((status) => <option key={status} value={status}>{animeStatusLabels[status]}</option>)}</select></label><label>目前看到第幾集<input max={anime.episodes ?? undefined} min="0" onChange={(event) => setWatchedEpisodes(Math.max(0, Number(event.target.value) || 0))} type="number" value={watchedEpisodes} /></label><label className="anime-check"><input checked={favorite} onChange={(event) => setFavorite(event.target.checked)} type="checkbox" /> 加入我的收藏</label><fieldset><legend>自訂標籤</legend><div className="anime-tag-picker">{tags.map((tag) => <label key={tag.id}><input checked={selectedTags.includes(tag.id)} onChange={() => setSelectedTags((ids) => ids.includes(tag.id) ? ids.filter((id) => id !== tag.id) : [...ids, tag.id])} type="checkbox" /> {tag.name}</label>)}</div><input onChange={(event) => setTagName(event.target.value)} placeholder="新標籤（輸入後一起儲存）" value={tagName} /></fieldset>{message && <p className="notice error">{message}</p>}<div className="dialog-actions"><button className="button" disabled={pending} onClick={() => void submit()} type="button">{pending ? "儲存中…" : existing ? "儲存更新" : "加入我的動漫"}</button><button className="secondary-button" disabled={pending} onClick={onClose} type="button">取消</button></div></div>}</ModalDialog>;
}

function AnimeDetailDialog({ anime, tags, onClose, onSaved, onRemove }: { anime: AnimeLibraryItem; tags: AnimeTag[]; onClose: () => void; onSaved: () => void; onRemove: () => void }) {
  const [watchStatus, setWatchStatus] = useState<AnimeWatchStatus>(anime.watchStatus); const [rating, setRating] = useState(anime.rating?.toString() ?? ""); const [notes, setNotes] = useState(anime.notes ?? ""); const [favorite, setFavorite] = useState(anime.favorite); const [selectedTags, setSelectedTags] = useState<string[]>(anime.tags.map((tag) => tag.id)); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const save = async () => { setPending(true); setMessage(null); try { await request("/api/anime/library", { method: "PATCH", body: JSON.stringify({ id: anime.id, watchStatus, rating: rating === "" ? null : Number(rating), notes, favorite, tagIds: selectedTags }) }); await onSaved(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "無法儲存修改。"); } finally { setPending(false); } };
  return <ModalDialog onClose={onClose} open={Boolean(anime)} pending={pending} title="動漫詳細資訊">{anime && <div className="anime-detail"><div className="anime-detail-hero">{anime.bannerUrl && <img alt="" src={anime.bannerUrl} />}<div><Cover anime={anime} /><div><StatusPill status={anime.watchStatus} /><h3>{anime.title}</h3><p>{anime.titleJapanese || anime.titleEnglish || anime.originalTitle}</p><p className="anime-detail-progress">{anime.watchedEpisodes} / {anime.episodes ?? "?"} 集 · 最後觀看 {day(anime.lastWatchedAt)}</p></div></div></div><div className="anime-detail-metadata"><span>{anime.releaseYear ?? "年份未提供"}</span><span>{anime.animeType ?? "類型未提供"}</span><span>{anime.episodes ? `${anime.episodes} 集` : "集數未定"}</span><span>網站評分 {anime.publicScore?.toFixed(1) ?? "—"}</span></div>{anime.synopsis && <section><h4>劇情介紹</h4><p>{anime.synopsis}</p></section>}{anime.genres.length > 0 && <section><h4>類型</h4><div className="anime-tags">{anime.genres.map((genre) => <span key={genre}>{genre}</span>)}</div></section>}<div className="anime-edit-grid"><label>觀看狀態<select onChange={(event) => setWatchStatus(event.target.value as AnimeWatchStatus)} value={watchStatus}>{statusOrder.map((status) => <option key={status} value={status}>{animeStatusLabels[status]}</option>)}</select></label><label>我的評分（0–10）<input max="10" min="0" onChange={(event) => setRating(event.target.value)} step="0.5" type="number" value={rating} /></label></div><label className="anime-check"><input checked={favorite} onChange={(event) => setFavorite(event.target.checked)} type="checkbox" /> 收藏這部動漫</label><fieldset><legend>我的標籤</legend><div className="anime-tag-picker">{tags.map((tag) => <label key={tag.id}><input checked={selectedTags.includes(tag.id)} onChange={() => setSelectedTags((ids) => ids.includes(tag.id) ? ids.filter((id) => id !== tag.id) : [...ids, tag.id])} type="checkbox" /> {tag.name}</label>)}</div></fieldset><label>私人備註<textarea onChange={(event) => setNotes(event.target.value)} placeholder="例如：第二季開始變得超好看，之後要補劇場版。" rows={4} value={notes} /></label>{message && <p className="notice error">{message}</p>}<div className="dialog-actions anime-detail-actions"><button className="button" disabled={pending} onClick={() => void save()} type="button">{pending ? "儲存中…" : "儲存修改"}</button><button className="secondary-button" disabled={pending} onClick={onRemove} type="button">移至垃圾桶</button></div></div>}</ModalDialog>;
}
