"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { FolderLockKind, FolderLockMode } from "@/lib/folder-locks/types";

type Folder = { id: string; name: string; is_locked?: boolean; lock_mode?: FolderLockMode | null };
type Kind = Exclude<FolderLockKind, "bookmark"> | "bookmark";
const sources: { kind: Kind; label: string; url: string; key: string }[] = [{ kind: "bookmark", label: "收藏", url: "/api/bookmarks", key: "folders" }, { kind: "note", label: "筆記", url: "/api/notes", key: "folders" }, { kind: "code", label: "程式碼", url: "/api/code", key: "folders" }, { kind: "file", label: "檔案", url: "/api/files", key: "folders" }, { kind: "photo", label: "照片", url: "/api/photos", key: "folders" }];

export function FolderLockSecuritySettings() {
  const [folders, setFolders] = useState<{ kind: Kind; label: string; folder: Folder }[]>([]); const [selectedKey, setSelectedKey] = useState(""); const [mode, setMode] = useState<FolderLockMode>("pin4"); const [password, setPassword] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let alive = true; void Promise.all(sources.map(async (source) => { const response = await fetch(source.url, { cache: "no-store" }); const body = await response.json().catch(() => null); return (body?.[source.key] ?? []).map((folder: Folder) => ({ kind: source.kind, label: source.label, folder })); })).then((groups) => { if (alive) setFolders(groups.flat()); }).catch(() => { if (alive) setError("無法讀取資料夾清單。"); }); return () => { alive = false; }; }, []);
  const selected = useMemo(() => folders.find((item) => `${item.kind}:${item.folder.id}` === selectedKey) ?? null, [folders, selectedKey]);
  async function configure(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setPending(true); setError(null); try { const response = await fetch("/api/folder-locks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "configure", kind: selected.kind, folderId: selected.folder.id, mode, password }) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? "無法設定資料夾鎖定。"); setFolders((current) => current.map((item) => item === selected ? { ...item, folder: { ...item.folder, is_locked: true, lock_mode: mode } } : item)); setPassword(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法設定資料夾鎖定。"); } finally { setPending(false); } }
  async function remove() { if (!selected) return; setPending(true); setError(null); try { const response = await fetch("/api/folder-locks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "remove", kind: selected.kind, folderId: selected.folder.id }) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? "無法解除鎖定。"); setFolders((current) => current.map((item) => item === selected ? { ...item, folder: { ...item.folder, is_locked: false, lock_mode: null } } : item)); setPassword(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法解除鎖定。"); } finally { setPending(false); } }
  return <section className="folder-lock-security"><p className="eyebrow">FOLDER PROTECTION</p><h2>資料夾 PIN 鎖定</h2><p>選擇收藏、筆記、程式碼、檔案或照片資料夾後，可設定獨立的 4 位、6 位 PIN 或複雜密碼。</p><label>要保護的資料夾<select onChange={(event) => setSelectedKey(event.target.value)} value={selectedKey}><option value="">選擇資料夾</option>{folders.map(({ kind, label, folder }) => <option key={`${kind}:${folder.id}`} value={`${kind}:${folder.id}`}>{folder.is_locked ? "🔒 " : ""}{folder.name} — {label}</option>)}</select></label>{selected && <form onSubmit={configure}><label>密碼類型<select onChange={(event) => setMode(event.target.value as FolderLockMode)} value={mode}><option value="pin4">4 位數 PIN 碼</option><option value="pin6">6 位數 PIN 碼</option><option value="password">英文＋數字＋符號密碼</option></select></label><label>{mode === "password" ? "新密碼（至少 10 字元）" : `PIN 碼（${mode === "pin4" ? 4 : 6} 位數）`}<input autoComplete="new-password" inputMode={mode === "password" ? undefined : "numeric"} maxLength={mode === "password" ? 128 : mode === "pin4" ? 4 : 6} onChange={(event) => setPassword(event.target.value)} pattern={mode === "password" ? undefined : "[0-9]*"} required type="password" value={password} /></label><div className="dialog-actions"><button className="button" disabled={pending} type="submit">{pending ? "處理中…" : selected.folder.is_locked ? "變更密碼" : "鎖住資料夾"}</button>{selected.folder.is_locked && <button className="delete-button" disabled={pending} onClick={() => void remove()} type="button">解除鎖定</button>}</div></form>}{error && <p className="notice error">{error}</p>}</section>;
}
