"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { CollectionCategory, CollectionNavigation, CollectionView } from "@/components/content/collection-navigation";
import { CoverImageField, type CoverSelection, uploadCover } from "@/components/content/cover-image-field";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { ModalDialog, OperationStatus } from "@/components/ui/modal-dialog";
import type { FilesWorkspaceData } from "@/lib/files/types";

const maxFileBytes = 52_428_800;
const formatBytes = (value: number) => value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KB` : `${(value / (1024 * 1024)).toFixed(1)} MB`;
async function sha256(file: File) { const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, "0")).join(""); }

export function FilesWorkspace({ initialData, createMode = false }: { initialData: FilesWorkspaceData; createMode?: boolean }) {
  const router = useRouter();
  const [data, setData] = useState(initialData); const [query, setQuery] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [deletingId, setDeletingId] = useState<string | null>(null); const [view, setView] = useState<CollectionView>("all"); const [category, setCategory] = useState<CollectionCategory>("all"); const [cover, setCover] = useState<CoverSelection>(null); const [selectedId, setSelectedId] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/files", { cache: "no-store" }); if (!response.ok) { setError("目前無法讀取檔案。"); return; } setData(await response.json() as FilesWorkspaceData); }, []);
  useEffect(() => { if (createMode) void load(); }, [createMode, load]);
  const files = useMemo(() => data.files.filter((file) => { if (view === "trash" ? !file.deletedAt : Boolean(file.deletedAt)) return false; if (view === "all" && file.archived) return false; if (view === "favorite" && (!file.favorite || file.archived)) return false; if (view === "pinned" && (!file.pinned || file.archived)) return false; if (view === "archived" && !file.archived) return false; if (view.startsWith("folder:") && (file.archived || file.folder?.id !== view.slice(7))) return false; if (category === "unclassified" && file.category) return false; if (category !== "all" && category !== "unclassified" && file.category?.id !== category) return false; return `${file.title} ${file.description ?? ""} ${file.originalFilename}`.toLowerCase().includes(query.toLowerCase()); }), [category, data.files, query, view]);
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const file = form.get("file"); if (!(file instanceof File) || !file.size) { setError("請選擇檔案。"); return; } if (file.size > maxFileBytes) { setError("單一檔案上限為 50 MB。"); return; } setPending(true); setError(null); try { const hash = await sha256(file); const ticketResponse = await fetch("/api/files/upload-url", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ originalFilename: file.name, mimeType: file.type || "application/octet-stream", byteSize: file.size, sha256: hash }) }); const ticket = await ticketResponse.json(); if (!ticketResponse.ok) throw new Error(ticket.error ?? "無法準備上傳。"); const { error: uploadError } = await createClient().storage.from("vault-files").uploadToSignedUrl(ticket.storagePath, ticket.token, file, { contentType: file.type || "application/octet-stream" }); if (uploadError) throw uploadError; const coverTicket = await uploadCover(cover); const completeResponse = await fetch("/api/files", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticket: ticket.ticket, title: String(form.get("title") || file.name), description: String(form.get("description") || ""), categoryId: String(form.get("categoryId") || "") || null, contentFolderId: String(form.get("contentFolderId") || "") || null, favorite: form.get("favorite") === "on", pinned: form.get("pinned") === "on", archived: form.get("archived") === "on", coverTicket, tags: [] }) }); const completed = await completeResponse.json(); if (!completeResponse.ok) throw new Error(completed.error ?? "無法完成上傳。"); if (createMode) { router.replace("/files"); router.refresh(); } else { formElement.reset(); setCover(null); await load(); } } catch (cause) { setError(cause instanceof Error ? cause.message : "無法上傳檔案。"); } finally { setPending(false); } }
  async function download(id: string) { setError(null); const response = await fetch(`/api/files?download=${encodeURIComponent(id)}`, { cache: "no-store" }); const result = await response.json().catch(() => null); if (!response.ok || !result?.url) { setError(result?.error ?? "無法準備下載。"); return; } window.location.assign(result.url); }
  async function remove() { if (!deletingId) return; setPending(true); setError(null); try { const response = await fetch("/api/files", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: deletingId }) }); if (!response.ok) throw new Error(); setDeletingId(null); setSelectedId(null); await load(); } catch { setError("無法永久刪除檔案。"); } finally { setPending(false); } }
  async function action(id: string, actionName: "trash" | "restore") { setPending(true); setError(null); try { const response = await fetch("/api/files", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action: actionName }) }); if (!response.ok) throw new Error(); setSelectedId(null); await load(); } catch { setError("無法更新檔案狀態。"); } finally { setPending(false); } }
  const uploadForm = <form className="file-upload-form" onSubmit={upload}><div><p className="eyebrow">PRIVATE FILE STORAGE</p><h2>上傳檔案</h2><p>檔案直接傳至私有儲存空間，最大 50 MB。</p></div><input aria-label="選擇檔案" name="file" required type="file" /><input aria-label="檔案標題" name="title" placeholder="檔案標題（未填則使用檔名）" /><textarea aria-label="檔案說明" name="description" placeholder="說明（選填）" rows={2} /><div className="file-upload-meta"><select aria-label="分類" defaultValue="" name="categoryId"><option value="">未分類</option>{data.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><details className="collection-settings"><summary>收藏設定 <small>可複選</small></summary><div className="collection-settings-menu"><label><input name="favorite" type="checkbox" /> 我的最愛</label><label><input name="pinned" type="checkbox" /> 置頂</label><label><input name="archived" type="checkbox" /> 封存</label><div className="collection-settings-divider" /><span>資料夾（選擇一個）</span><label><input defaultChecked name="contentFolderId" type="radio" value="" /> 不放入資料夾</label>{data.folders.filter((folder) => folder.is_visible).map((folder) => <label key={folder.id}><input name="contentFolderId" type="radio" value={folder.id} /> {folder.name}</label>)}</div></details><CoverImageField onChange={setCover} /><button className="button" disabled={pending} type="submit">{pending ? "上傳中…" : "上傳至保管庫"}</button></form>;
  if (createMode) return <section className="files-workspace create-only">{pending && <OperationStatus label="正在處理檔案…" />}{error && <p className="notice error" role="alert">{error}</p>}{uploadForm}</section>;
  const selected = data.files.find((item) => item.id === selectedId) ?? null;
  return <section className="library-workspace">{pending && <OperationStatus label="正在處理檔案…" />}{error && <p className="notice error" role="alert">{error}</p>}<div className="library-heading"><div><p className="eyebrow">SECURE FILES</p><h2>檔案保管</h2></div></div><CollectionNavigation categories={data.categories} category={category} folders={data.folders} items={data.files} setCategory={setCategory} setView={setView} storageKey="personal-vault:file-system-folders:v1" view={view} /><input aria-label="搜尋檔案" className="note-search" onChange={(event) => setQuery(event.target.value)} placeholder="搜尋檔案名稱或說明" value={query} /><div className="content-item-list">{files.map((file) => <article className="content-item-card" key={file.id}><button className="content-item-open" onClick={() => setSelectedId(file.id)} type="button">{file.coverImageUrl ? <img alt="" src={file.coverImageUrl} /> : <span className="content-cover-placeholder">檔案</span>}<div><p className="bookmark-meta">{file.category?.name ?? "未分類"}{file.folder && ` · ${file.folder.name}`}</p><h3>{file.title}</h3><p>{file.description || `${file.originalFilename} · ${formatBytes(file.byteSize)}`}</p></div></button></article>)}{files.length === 0 && <p className="lead">此清單尚未找到檔案。</p>}</div><ModalDialog onClose={() => setSelectedId(null)} open={Boolean(selected)} pending={pending} title={selected?.title ?? "檔案資訊"}>{selected && <><p className="detail-content">{selected.description || "沒有說明。"}</p><p className="bookmark-meta">{selected.originalFilename} · {formatBytes(selected.byteSize)}</p><div className="dialog-actions"><button className="secondary-button" onClick={() => void download(selected.id)} type="button">下載</button>{selected.deletedAt ? <><button className="button" onClick={() => void action(selected.id, "restore")} type="button">還原</button><button className="delete-button" onClick={() => setDeletingId(selected.id)} type="button">永久刪除</button></> : <button className="delete-button" onClick={() => void action(selected.id, "trash")} type="button">刪除</button>}</div></>}</ModalDialog><ConfirmDialog description="此檔案將從私有儲存空間永久刪除，無法還原。" error={error} onCancel={() => setDeletingId(null)} onConfirm={() => { void remove(); }} open={Boolean(deletingId)} pending={pending} title="永久刪除檔案？" /></section>;
}
