"use client";

import Link from "next/link";
import { FormEvent, useCallback, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { CodeSnippet, CodeWorkspaceData } from "@/lib/code/types";

export function CodeWorkspace({ initialData, createMode = false }: { initialData: CodeWorkspaceData; createMode?: boolean }) {
  const router = useRouter(); const [data, setData] = useState(initialData); const [query, setQuery] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const [selected, setSelected] = useState<CodeSnippet | null>(null); const [editing, setEditing] = useState<CodeSnippet | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/code", { cache: "no-store" }); if (!response.ok) { setError("目前無法讀取程式碼。"); return; } setData(await response.json() as CodeWorkspaceData); }, []);
  const list = useMemo(() => data.snippets.filter((item) => `${item.title} ${item.language} ${item.description ?? ""}`.toLowerCase().includes(query.toLowerCase())), [data.snippets, query]);
  function body(form: FormData, id?: string) { return { ...(id ? { id } : {}), title: form.get("title"), description: form.get("description"), language: form.get("language"), sourceCode: form.get("sourceCode"), categoryId: form.get("categoryId") || null, tags: String(form.get("tags") ?? "").split(",").map((tag) => tag.trim()).filter(Boolean) }; }
  async function save(event: FormEvent<HTMLFormElement>, id?: string) { event.preventDefault(); setPending(true); const response = await fetch("/api/code", { method: id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body(new FormData(event.currentTarget), id)) }); setPending(false); if (!response.ok) { setError("無法儲存程式碼。"); return; } if (!id) { router.replace("/code"); router.refresh(); return; } setEditing(null); setSelected(null); await load(); }
  async function remove(id: string) { if (!window.confirm("確定要刪除這段程式碼嗎？")) return; setPending(true); const response = await fetch("/api/code", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); setPending(false); if (!response.ok) { setError("無法刪除程式碼。"); return; } setSelected(null); await load(); }
  const editor = (snippet?: CodeSnippet) => <form className="code-editor" onSubmit={(event) => void save(event, snippet?.id)}><input defaultValue={snippet?.title ?? ""} name="title" placeholder="程式碼標題" required /><textarea defaultValue={snippet?.description ?? ""} name="description" placeholder="說明（選填）" rows={2} /><div className="code-editor-meta"><input defaultValue={snippet?.language ?? "text"} name="language" placeholder="語言，例如 TypeScript" required /><select defaultValue={snippet?.category?.id ?? ""} name="categoryId"><option value="">未分類</option>{data.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input defaultValue={snippet?.tags.map((tag) => tag.name).join(", ") ?? ""} name="tags" placeholder="標籤，以逗號分隔" /></div><textarea className="source-code" defaultValue={snippet?.sourceCode ?? ""} name="sourceCode" placeholder="貼上程式碼…" required rows={15} /><div className="dialog-actions"><button className="button" disabled={pending} type="submit">{pending ? "儲存中…" : snippet ? "儲存修改" : "儲存程式碼"}</button>{snippet && <button className="secondary-button" onClick={() => setEditing(null)} type="button">取消</button>}</div></form>;
  if (createMode) return <section className="code-workspace create-only">{error && <p className="notice error">{error}</p>}{editor()}</section>;
  return <section className="library-workspace">{error && <p className="notice error">{error}</p>}<div className="library-heading"><div><p className="eyebrow">CODE SNIPPETS</p><h2>程式碼片段</h2></div><Link className="button compact" href="/create/code">＋ 新增資料</Link></div><input aria-label="搜尋程式碼" className="note-search" onChange={(event) => setQuery(event.target.value)} placeholder="搜尋程式碼標題或語言" value={query} /><div className="library-list">{list.map((item) => <article className="library-card code-list-card" key={item.id}><button className="library-open" onClick={() => setSelected(item)} type="button"><p className="bookmark-meta">{item.language} · {item.category?.name ?? "未分類"}</p><h3>{item.title}</h3></button><div className="center-actions"><button className="secondary-button" onClick={() => setEditing(item)} type="button">修改</button><button className="delete-button" onClick={() => void remove(item.id)} type="button">刪除</button></div></article>)}{list.length === 0 && <p className="lead">尚無程式碼片段。</p>}</div>{selected && <section aria-modal="true" className="inline-dialog detail-dialog" role="dialog"><h2>{selected.title}</h2><pre className="detail-code">{selected.sourceCode}</pre><div className="dialog-actions"><button className="secondary-button" onClick={() => setSelected(null)} type="button">關閉</button></div></section>}{editing && <section aria-modal="true" className="inline-dialog edit-dialog" role="dialog"><h2>修改程式碼</h2>{editor(editing)}</section>}</section>;
}
