"use client";
import { useState } from "react";
import type { VocabularyCard } from "@/lib/vocabulary/types";

// A review records what happened, not a self-assigned difficulty. The server
// derives the mastery level from the complete answer history after the session.
export type LocalReview = { cardId: string; answerResult: boolean; durationMs: number; occurrenceIndex: number; mode: "review" | "quiz" };

export function FlashcardReview({ cards, direction, onComplete, pending }: { cards: VocabularyCard[]; direction: "native" | "reverse"; onComplete: (reviews: LocalReview[]) => Promise<void>; pending: boolean }) {
  const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const [exampleMode, setExampleMode] = useState(false); const [reviews, setReviews] = useState<LocalReview[]>([]); const [startedAt, setStartedAt] = useState(() => Date.now());
  const card = cards[index];
  if (!cards.length) return <div className="vocabulary-empty"><strong>目前沒有可複習的單字</strong><p>先將單字加入學習中，再開始一輪複習。</p></div>;
  if (!card) return <section className="flashcard-session"><div className="vocabulary-empty"><strong>已完成 {reviews.length} 個單字</strong><p>熟練度會在你按下儲存後一次更新，不會逐題寫入。</p><button className="button" disabled={pending} onClick={() => void onComplete(reviews)} type="button">{pending ? "儲存中…" : "儲存本次複習"}</button></div></section>;
  const example = card.examples[0]; const reverse = direction === "reverse" && card.language === "ja"; const meaning = card.primaryTranslation || card.meanings.map((item) => item.meaning).join("、") || "尚未填寫意思";
  function record(answerResult: boolean) { setReviews((current) => [...current, { cardId: card.id, answerResult, durationMs: Date.now() - startedAt, occurrenceIndex: index + 1, mode: "review" }]); setFlipped(false); setIndex((current) => current + 1); setStartedAt(Date.now()); }
  return <section className="flashcard-session"><div className="flashcard-progress"><span>{reverse ? "中文 → 日文複習" : "日文 → 中文複習"}</span><strong>{index + 1} / {cards.length}</strong></div><button className="secondary-button compact" disabled={!example} onClick={() => { setExampleMode((value) => !value); setFlipped(false); }} type="button">{exampleMode ? "一般模式" : "例句模式"}</button><button aria-label="翻轉單字卡" className={`flashcard${flipped ? " flipped" : ""}`} onClick={() => setFlipped((value) => !value)} type="button"><span className="flashcard-front"><small>{exampleMode ? "從例句猜單字" : reverse ? "中文意思" : card.language.toUpperCase()}</small><strong>{exampleMode && example ? example.sentence.replace(card.word, "＿＿＿") : reverse ? meaning : card.word}</strong><em>{exampleMode ? "點擊顯示答案" : reverse ? "點擊顯示日文答案" : card.reading || card.romaji || "點擊顯示答案"}</em></span><span className="flashcard-back"><small>{exampleMode ? example?.translationZhTw || example?.translation || "例句翻譯" : card.partOfSpeech || "Vocabulary"}</small><strong>{exampleMode ? card.word : reverse ? card.word : meaning}</strong><em>{exampleMode ? meaning : reverse ? card.reading || card.kana || "未設定讀音" : example?.sentence || card.notes || "沒有補充內容"}</em></span></button>{flipped ? <div className="review-outcome-actions"><p>你剛剛是否答對？系統會依答題紀錄自動判定熟練度。</p><button className="danger" onClick={() => record(false)} type="button">答錯</button><button className="success" onClick={() => record(true)} type="button">答對</button></div> : <button className="button flashcard-reveal" onClick={() => setFlipped(true)} type="button">顯示答案</button>}</section>;
}
