"use client";

import { FormEvent, useMemo, useState } from "react";
import type { BookmarksWorkspaceData } from "@/lib/bookmarks/types";
import type { NotesWorkspaceData } from "@/lib/notes/types";
import type { CodeWorkspaceData } from "@/lib/code/types";
import type { FilesWorkspaceData } from "@/lib/files/types";

type Tab = "bookmark" | "note" | "code" | "file";
type Item = { id: string; name: string; is_visible?: boolean };
const tabLabels: Record<Tab, string> = { bookmark: "收藏", note: "筆記", code: "程式碼", file: "檔案" };

function ItemManager({ api, items, kind, title, description, onChange }: { api: "/api/taxonomy" | "/api/content-folders"; items: Item[]; kind: string; title: string; description: string; onChange: (items: Item[]) => void }) {
  const [name, setName] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [value, setValue] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function mutate(method: "POST" | "PATCH" | "DELETE", body: object) { setPending(true); setError(null); try { const response = await fetch(api, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, ...body }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? "操作失敗。"); if (method === "POST" && payload?.item) onChange([...items, payload.item].sort((a, b) => a.name.localeCompare(b.name, "zh-Hant"))); else if (method === "PATCH") onChange(items.map((item) => item.id === (body as { id: string }).id ? { ...item, ...(body as { name?: string; visible?: boolean }) } : item)); else if (method === "DELETE") onChange(items.filter((item) => item.id !== (body as { id: string }).id)); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失敗。"); return false; } finally { setPending(false); } }
  async function create(event: FormEvent) { event.preventDefault(); if (name.trim() && await mutate("POST", { name: name.trim() })) setName(""); }
  return <section className="category-manager management-panel"><header className="manager-heading"><div><p className="eyebrow">{title.toUpperCase()}</p><h2>{title}</h2><p>{description}</p></div></header>{error && <p className="notice error">{error}</p>}<form className="category-create-row" onSubmit={create}><input onChange={(event) => setName(event.target.value)} placeholder={`新增${title}名稱`} value={name} /><button className="button compact" disabled={pending} type="submit">＋ 新增</button></form><div className="folder-list">{items.length ? items.map((item) => <article className="folder-row" key={item.id}><div>{editing === item.id ? <input autoFocus onChange={(event) => setValue(event.target.value)} value={value} /> : <><strong>{item.name}</strong>{item.is_visible !== undefined && <small>{item.is_visible ? "目前顯示於清單與選單" : "目前已隱藏"}</small>}</>}</div><div className="manager-actions">{editing === item.id ? <><button className="button compact" disabled={pending} onClick={() => { if (value.trim()) void mutate("PATCH", { id: item.id, name: value.trim() }).then((ok) => ok && setEditing(null)); }} type="button">儲存</button><button className="secondary-button compact" disabled={pending} onClick={() => setEditing(null)} type="button">取消</button></> : <>{item.is_visible !== undefined && <button className="secondary-button compact" disabled={pending} onClick={() => void mutate("PATCH", { id: item.id, visible: !item.is_visible })} type="button">{item.is_visible ? "隱藏" : "顯示"}</button>}<button className="secondary-button compact" disabled={pending} onClick={() => { setEditing(item.id); setValue(item.name); }} type="button">修改</button><button className="delete-button compact" disabled={pending} onClick={() => void mutate("DELETE", { id: item.id })} type="button">移除</button></>}</div></article>) : <p className="manager-empty">尚未建立項目。</p>}</div></section>;
}

export function CategoryFolderManagement({ bookmarks, code, files, notes }: { bookmarks: BookmarksWorkspaceData; notes: NotesWorkspaceData; code: CodeWorkspaceData; files: FilesWorkspaceData }) {
  const [tab, setTab] = useState<Tab>("bookmark");
  const [categories, setCategories] = useState<Item[]>(bookmarks.categories);
  const [bookmarkFolders, setBookmarkFolders] = useState<Item[]>(bookmarks.folders);
  const [noteFolders, setNoteFolders] = useState<Item[]>(notes.folders);
  const [codeFolders, setCodeFolders] = useState<Item[]>(code.folders);
  const [fileFolders, setFileFolders] = useState<Item[]>(files.folders);
  const folder = useMemo(() => tab === "bookmark" ? { api: "/api/taxonomy" as const, kind: "bookmark_folder", items: bookmarkFolders, update: setBookmarkFolders, title: "收藏資料夾" } : tab === "note" ? { api: "/api/content-folders" as const, kind: "note", items: noteFolders, update: setNoteFolders, title: "筆記資料夾" } : tab === "code" ? { api: "/api/content-folders" as const, kind: "code", items: codeFolders, update: setCodeFolders, title: "程式碼資料夾" } : { api: "/api/content-folders" as const, kind: "file", items: fileFolders, update: setFileFolders, title: "檔案資料夾" }, [bookmarkFolders, codeFolders, fileFolders, noteFolders, tab]);
  return <section className="management-workspace"><div className="management-tabs" role="tablist">{(Object.keys(tabLabels) as Tab[]).map((key) => <button aria-selected={tab === key} className={tab === key ? "active" : ""} key={key} onClick={() => setTab(key)} role="tab" type="button">{tabLabels[key]}</button>)}</div><div className="management-intro"><p className="eyebrow">{tabLabels[tab].toUpperCase()} ORGANIZATION</p><h2>管理 {tabLabels[tab]} 的類別與資料夾</h2><p>「未分類」固定存在；移除類別或資料夾不會刪除原本的內容，只會改為未分類或未放入資料夾。</p></div><div className="management-grid"><ItemManager api="/api/taxonomy" description="目前所有內容頁共用這套類別，修改後會立即同步到新增與修改表單。" items={categories} kind="category" onChange={setCategories} title="類別" /><ItemManager api={folder.api} description="資料夾只屬於目前選擇的內容類型，可隱藏、修改或移除。" items={folder.items} kind={folder.kind} onChange={folder.update} title={folder.title} /></div></section>;
}
