"use client";

import { FormEvent, useMemo, useState } from "react";
import type { BookmarksWorkspaceData } from "@/lib/bookmarks/types";
import type { NotesWorkspaceData } from "@/lib/notes/types";
import type { CodeWorkspaceData } from "@/lib/code/types";
import type { FilesWorkspaceData } from "@/lib/files/types";

type Tab = "bookmark" | "note" | "code" | "file";
type Item = { id: string; name: string; is_visible?: boolean };
type ContentItem = { category: { id: string } | null; folder: { id: string } | null; favorite: boolean; pinned: boolean; archived: boolean; deletedAt: string | null };
const tabLabels: Record<Tab, string> = { bookmark: "收藏", note: "筆記", code: "程式碼", file: "檔案" };
const smartKeys = ["favorite", "pinned", "archived", "trash"] as const;
type SmartKey = typeof smartKeys[number];
type SmartSettings = Record<SmartKey, { label: string; visible: boolean }>;
const smartDefaults: SmartSettings = { favorite: { label: "我的最愛", visible: true }, pinned: { label: "置頂", visible: true }, archived: { label: "封存", visible: true }, trash: { label: "垃圾桶", visible: true } };
const smartStorageKey = "personal-vault:bookmark-system-folders:v1";

function ItemManager({ api, fixedCount, items, kind, onChange, title, description, count }: { api: "/api/taxonomy" | "/api/content-folders"; fixedCount?: number; items: Item[]; kind: string; onChange: (items: Item[]) => void; title: string; description: string; count: (id: string) => number }) {
  const [name, setName] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [value, setValue] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function mutate(method: "POST" | "PATCH" | "DELETE", body: object) { setPending(true); setError(null); try { const response = await fetch(api, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, ...body }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? "操作失敗。"); if (method === "POST" && payload?.item) onChange([...items, payload.item].sort((a, b) => a.name.localeCompare(b.name, "zh-Hant"))); if (method === "PATCH") onChange(items.map((item) => item.id === (body as { id: string }).id ? { ...item, ...(body as { name?: string; visible?: boolean }) } : item)); if (method === "DELETE") onChange(items.filter((item) => item.id !== (body as { id: string }).id)); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失敗。"); return false; } finally { setPending(false); } }
  async function create(event: FormEvent) { event.preventDefault(); if (name.trim() && await mutate("POST", { name: name.trim() })) setName(""); }
  return <section className="category-manager management-panel"><header className="manager-heading"><div><p className="eyebrow">{title.toUpperCase()}</p><h2>{title}</h2><p>{description}</p></div></header>{error && <p className="notice error">{error}</p>}<form className="category-create-row" onSubmit={create}><input onChange={(event) => setName(event.target.value)} placeholder={`新增${title}名稱`} value={name} /><button className="button compact" disabled={pending} type="submit">＋ 新增</button></form><div className="folder-list">{fixedCount !== undefined && <article className="folder-row system-folder"><div><strong>未分類 <em>{fixedCount}</em></strong><small>固定保留，未指定類別的資料會顯示於此</small></div><span>固定保留</span></article>}{items.length ? items.map((item) => <article className="folder-row" key={item.id}><div>{editing === item.id ? <input autoFocus onChange={(event) => setValue(event.target.value)} value={value} /> : <><strong>{item.name} <em>{count(item.id)}</em></strong>{item.is_visible !== undefined && <small>{item.is_visible ? "目前顯示於清單與選單" : "目前已隱藏"}</small>}</>}</div><div className="manager-actions">{editing === item.id ? <><button className="button compact" disabled={pending} onClick={() => { if (value.trim()) void mutate("PATCH", { id: item.id, name: value.trim() }).then((ok) => ok && setEditing(null)); }} type="button">儲存</button><button className="secondary-button compact" disabled={pending} onClick={() => setEditing(null)} type="button">取消</button></> : <>{item.is_visible !== undefined && <button className="secondary-button compact" disabled={pending} onClick={() => void mutate("PATCH", { id: item.id, visible: !item.is_visible })} type="button">{item.is_visible ? "隱藏" : "顯示"}</button>}<button className="secondary-button compact" disabled={pending} onClick={() => { setEditing(item.id); setValue(item.name); }} type="button">修改</button><button className="delete-button compact" disabled={pending} onClick={() => void mutate("DELETE", { id: item.id })} type="button">移除</button></>}</div></article>) : <p className="manager-empty">尚未建立項目。</p>}</div></section>;
}

function SmartFolderManager({ items }: { items: ContentItem[] }) {
  const [settings, setSettings] = useState<SmartSettings>(() => { if (typeof window === "undefined") return smartDefaults; try { return { ...smartDefaults, ...JSON.parse(window.localStorage.getItem(smartStorageKey) ?? "{}") }; } catch { return smartDefaults; } });
  const [editing, setEditing] = useState<SmartKey | null>(null); const [value, setValue] = useState("");
  const count = (key: SmartKey) => key === "favorite" ? items.filter((item) => !item.deletedAt && item.favorite && !item.archived).length : key === "pinned" ? items.filter((item) => !item.deletedAt && item.pinned && !item.archived).length : key === "archived" ? items.filter((item) => !item.deletedAt && item.archived).length : items.filter((item) => item.deletedAt).length;
  function save(next: SmartSettings) { setSettings(next); window.localStorage.setItem(smartStorageKey, JSON.stringify(next)); }
  return <section className="category-manager management-panel smart-folder-manager"><header className="manager-heading"><div><p className="eyebrow">SMART FOLDERS</p><h2>常駐清單</h2><p>「全部」固定顯示；其餘清單可改名或隱藏。設定會立即套用到收藏清單。</p></div></header><div className="folder-list">{smartKeys.map((key) => <article className="folder-row" key={key}><div>{editing === key ? <input autoFocus onChange={(event) => setValue(event.target.value)} value={value} /> : <><strong>{settings[key].label} <em>{count(key)}</em></strong><small>{settings[key].visible ? "目前顯示於收藏清單" : "目前已隱藏"}</small></>}</div><div className="manager-actions">{editing === key ? <><button className="button compact" onClick={() => { if (value.trim()) { save({ ...settings, [key]: { ...settings[key], label: value.trim().slice(0, 20) } }); setEditing(null); } }} type="button">儲存</button><button className="secondary-button compact" onClick={() => setEditing(null)} type="button">取消</button></> : <><button className="secondary-button compact" onClick={() => { setEditing(key); setValue(settings[key].label); }} type="button">修改</button><button className={settings[key].visible ? "delete-button compact" : "secondary-button compact"} onClick={() => save({ ...settings, [key]: { ...settings[key], visible: !settings[key].visible } })} type="button">{settings[key].visible ? "隱藏" : "顯示"}</button></>}</div></article>)}</div></section>;
}

export function CategoryFolderManagement({ bookmarks, code, files, notes }: { bookmarks: BookmarksWorkspaceData; notes: NotesWorkspaceData; code: CodeWorkspaceData; files: FilesWorkspaceData }) {
  const [tab, setTab] = useState<Tab>("bookmark"); const [categories, setCategories] = useState<Item[]>(bookmarks.categories); const [bookmarkFolders, setBookmarkFolders] = useState<Item[]>(bookmarks.folders); const [noteFolders, setNoteFolders] = useState<Item[]>(notes.folders); const [codeFolders, setCodeFolders] = useState<Item[]>(code.folders); const [fileFolders, setFileFolders] = useState<Item[]>(files.folders);
  const selected = useMemo(() => tab === "bookmark" ? { items: bookmarks.bookmarks as ContentItem[], folders: bookmarkFolders, update: setBookmarkFolders, api: "/api/taxonomy" as const, kind: "bookmark_folder", title: "收藏資料夾" } : tab === "note" ? { items: notes.notes as ContentItem[], folders: noteFolders, update: setNoteFolders, api: "/api/content-folders" as const, kind: "note", title: "筆記資料夾" } : tab === "code" ? { items: code.snippets as ContentItem[], folders: codeFolders, update: setCodeFolders, api: "/api/content-folders" as const, kind: "code", title: "程式碼資料夾" } : { items: files.files as ContentItem[], folders: fileFolders, update: setFileFolders, api: "/api/content-folders" as const, kind: "file", title: "檔案資料夾" }, [bookmarkFolders, bookmarks.bookmarks, code.snippets, codeFolders, fileFolders, files.files, noteFolders, notes.notes, tab]);
  const active = selected.items.filter((item) => !item.deletedAt); const categoryCount = (id: string) => active.filter((item) => item.category?.id === id).length; const folderCount = (id: string) => selected.items.filter((item) => item.folder?.id === id).length;
  return <section className="management-workspace"><div className="management-tabs" role="tablist">{(Object.keys(tabLabels) as Tab[]).map((key) => <button aria-selected={tab === key} className={tab === key ? "active" : ""} key={key} onClick={() => setTab(key)} role="tab" type="button">{tabLabels[key]}</button>)}</div><div className="management-intro"><p className="eyebrow">{tabLabels[tab].toUpperCase()} ORGANIZATION</p><h2>管理 {tabLabels[tab]} 的類別與資料夾</h2><p>未分類為固定類別。新增、修改、隱藏或移除後，畫面與下次開啟表單都會直接使用最新設定。</p></div><div className="management-grid"><ItemManager api="/api/taxonomy" count={categoryCount} description="目前所有內容頁共用這套類別；數字顯示目前分頁中正在使用此類別的資料筆數。" fixedCount={active.filter((item) => !item.category).length} items={categories} kind="category" onChange={setCategories} title="類別" /><ItemManager api={selected.api} count={folderCount} description="資料夾只屬於目前選擇的內容類型；數字包含該資料夾內的所有資料。" items={selected.folders} kind={selected.kind} onChange={selected.update} title={selected.title} /></div>{tab === "bookmark" && <SmartFolderManager items={bookmarks.bookmarks} />}</section>;
}
