"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { FolderUnlockDialog } from "@/components/content/folder-unlock-dialog";
import { ModalDialog, OperationStatus } from "@/components/ui/modal-dialog";
import type { FolderLockKind, FolderLockMode } from "@/lib/folder-locks/types";

export type CollectionView = "all" | "favorite" | "pinned" | "archived" | "trash" | `folder:${string}`;
export type CollectionCategory = "all" | "unclassified" | string;
type ContentKind = "bookmark" | "note" | "code" | "file" | "photo";
type Item = { category: { id: string } | null; folder: { id: string } | null; favorite: boolean; pinned: boolean; archived: boolean; deletedAt: string | null };
type Folder = { id: string; name: string; sort_order?: number; is_visible: boolean; is_locked?: boolean; lock_mode?: FolderLockMode | null };
type Category = { id: string; name: string; sort_order?: number; folder_id: string | null };
type Entity = "category" | "folder";

function contentKind(key: string): ContentKind { return key.includes(":note:") ? "note" : key.includes(":code:") ? "code" : key.includes(":file:") ? "file" : key.includes(":photo:") ? "photo" : "bookmark"; }
function sorted<T extends { name: string; sort_order?: number }>(items: T[]) { return [...items].sort((a, b) => (a.sort_order ?? 0) - (b.sort_order ?? 0) || a.name.localeCompare(b.name, "zh-Hant")); }
function sameOrder<T extends { id: string }>(left: T[], right: T[]) { return left.length === right.length && left.every((item, index) => item.id === right[index]?.id); }

export function CollectionNavigation({ categories, category, folders, items, setCategory, setView, storageKey, view }: { categories: Category[]; category: CollectionCategory; folders: Folder[]; items: Item[]; setCategory: (value: CollectionCategory) => void; setView: (value: CollectionView) => void; storageKey: string; view: CollectionView }) {
  const kind = contentKind(storageKey); const folderId = view.startsWith("folder:") ? view.slice(7) : null;
  const [localCategories, setLocalCategories] = useState(categories); const [localFolders, setLocalFolders] = useState(folders); const [lockedFolder, setLockedFolder] = useState<Folder | null>(null);
  const [dialog, setDialog] = useState<"category-add" | "category-more" | "category-edit" | "folder-add" | "folder-more" | "folder-edit" | null>(null);
  const [name, setName] = useState(""); const [query, setQuery] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  const [draftCategories, setDraftCategories] = useState<Category[]>([]); const [draftFolders, setDraftFolders] = useState<Folder[]>([]); const [removedCategoryIds, setRemovedCategoryIds] = useState<string[]>([]); const [removedFolderIds, setRemovedFolderIds] = useState<string[]>([]);
  const [rename, setRename] = useState<{ entity: Entity; id: string; value: string } | null>(null); const [dragging, setDragging] = useState<{ entity: Entity; id: string } | null>(null); const timer = useRef<number | null>(null);
  useEffect(() => { setLocalCategories(categories); }, [categories]); useEffect(() => { setLocalFolders(folders); }, [folders]);
  useEffect(() => { const target = window.sessionStorage.getItem(`${storageKey}:unlock-target`); if (target && localFolders.some((folder) => folder.id === target)) { window.sessionStorage.removeItem(`${storageKey}:unlock-target`); setView(`folder:${target}`); } }, [localFolders, setView, storageKey]);
  const active = items.filter((item) => !item.deletedAt && !item.archived); const scopeItems = folderId ? active.filter((item) => item.folder?.id === folderId) : active.filter((item) => !item.folder); const scopeCategories = sorted(localCategories.filter((item) => (item.folder_id ?? null) === folderId));
  const visibleCategories = scopeCategories.filter((item) => item.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())); const countFolder = (id: string) => active.filter((item) => item.folder?.id === id).length; const countCategory = (id: string) => scopeItems.filter((item) => item.category?.id === id).length; const unorganizedCount = active.filter((item) => !item.folder).length; const trashCount = items.filter((item) => item.deletedAt).length;
  function select(next: CollectionView, folder?: Folder) { if (folder?.is_locked) { setLockedFolder(folder); return; } setCategory("all"); setView(next); }
  function close() { if (!pending) { setDialog(null); setName(""); setError(null); } }
  async function api(url: string, method: "POST" | "PATCH" | "DELETE", body: object) { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.error ?? "無法完成操作。"); return result; }
  function notify() { window.dispatchEvent(new CustomEvent("personal-vault:taxonomy-updated", { detail: kind })); }
  async function addCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!name.trim()) return; setPending(true); setError(null); try { const result = await api("/api/taxonomy", "POST", { kind: "category", contentKind: kind, folderId, name: name.trim() }); if (result.item) setLocalCategories((current) => [...current, result.item]); notify(); close(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法新增類別。"); } finally { setPending(false); } }
  const folderEndpoint = kind === "bookmark" ? "/api/taxonomy" : "/api/content-folders"; const folderPayload = (payload: Record<string, unknown>) => kind === "bookmark" ? { kind: "bookmark_folder", contentKind: kind, ...payload } : { kind, ...payload };
  async function addFolder(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!name.trim()) return; setPending(true); setError(null); try { const result = await api(folderEndpoint, "POST", folderPayload({ name: name.trim() })); if (result.item) setLocalFolders((current) => [...current, result.item]); notify(); close(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法新增資料夾。"); } finally { setPending(false); } }
  function openManager(entity: Entity) { setError(null); setRename(null); setDragging(null); if (entity === "category") { setDraftCategories(scopeCategories); setRemovedCategoryIds([]); setDialog("category-edit"); } else { setDraftFolders(sorted(localFolders)); setRemovedFolderIds([]); setDialog("folder-edit"); } }
  function beginLongPress(entity: Entity, id: string) { if (timer.current) window.clearTimeout(timer.current); timer.current = window.setTimeout(() => setDragging({ entity, id }), 420); }
  function endLongPress() { if (timer.current) window.clearTimeout(timer.current); timer.current = null; setDragging(null); }
  function moveDraft(entity: Entity, fromId: string, toId: string) { if (fromId === toId) return; if (entity === "category") setDraftCategories((current) => { const from = current.findIndex((item) => item.id === fromId); const to = current.findIndex((item) => item.id === toId); if (from < 0 || to < 0) return current; const next = [...current]; const [moving] = next.splice(from, 1); next.splice(to, 0, moving); return next; }); else setDraftFolders((current) => { const from = current.findIndex((item) => item.id === fromId); const to = current.findIndex((item) => item.id === toId); if (from < 0 || to < 0) return current; const next = [...current]; const [moving] = next.splice(from, 1); next.splice(to, 0, moving); return next; }); }
  function removeDraft(entity: Entity, id: string) { if (entity === "category") { setDraftCategories((current) => current.filter((item) => item.id !== id)); setRemovedCategoryIds((current) => [...current, id]); if (category === id) setCategory("all"); } else { setDraftFolders((current) => current.filter((item) => item.id !== id)); setRemovedFolderIds((current) => [...current, id]); if (view === `folder:${id}`) select("all"); } }
  function renameDraft(entity: Entity, id: string, value: string) { if (entity === "category") setDraftCategories((current) => current.map((item) => item.id === id ? { ...item, name: value.trim().slice(0, 80) } : item)); else setDraftFolders((current) => current.map((item) => item.id === id ? { ...item, name: value.trim().slice(0, 80) } : item)); setRename(null); }
  async function commitManager(entity: Entity) { if (entity === "category") { const original = scopeCategories; const draft = draftCategories; const changed = !sameOrder(original, draft) || draft.some((item) => original.find((origin) => origin.id === item.id)?.name !== item.name) || removedCategoryIds.length > 0; if (!changed) { close(); return; } setPending(true); setError(null); try { for (const [sortOrder, item] of draft.entries()) { const origin = original.find((value) => value.id === item.id); if (!origin || origin.name !== item.name || (origin.sort_order ?? original.indexOf(origin)) !== sortOrder) await api("/api/taxonomy", "PATCH", { kind: "category", contentKind: kind, id: item.id, name: item.name, sortOrder }); } for (const id of removedCategoryIds) await api("/api/taxonomy", "DELETE", { kind: "category", contentKind: kind, id }); setLocalCategories((current) => [...current.filter((item) => (item.folder_id ?? null) !== folderId), ...draft.map((item, sortOrder) => ({ ...item, sort_order: sortOrder }))]); notify(); close(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法儲存整理結果。"); } finally { setPending(false); } return; } const original = sorted(localFolders); const draft = draftFolders; const changed = !sameOrder(original, draft) || draft.some((item) => original.find((origin) => origin.id === item.id)?.name !== item.name) || removedFolderIds.length > 0; if (!changed) { close(); return; } setPending(true); setError(null); try { for (const [sortOrder, item] of draft.entries()) { const origin = original.find((value) => value.id === item.id); if (!origin || origin.name !== item.name || (origin.sort_order ?? original.indexOf(origin)) !== sortOrder) await api(folderEndpoint, "PATCH", folderPayload({ id: item.id, name: item.name, sortOrder })); } for (const id of removedFolderIds) await api(folderEndpoint, "DELETE", folderPayload({ id })); setLocalFolders(draft.map((item, sortOrder) => ({ ...item, sort_order: sortOrder }))); notify(); close(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法儲存整理結果。"); } finally { setPending(false); } }
  function closeManager(entity: Entity) { endLongPress(); if (!pending) void commitManager(entity); }
  function managerItems(entity: Entity) { const source = entity === "category" ? draftCategories : draftFolders; return <div className="taxonomy-manager-list">{source.map((item) => <article className={dragging?.entity === entity && dragging.id === item.id ? "taxonomy-manager-item dragging" : "taxonomy-manager-item"} key={item.id} onPointerDown={() => beginLongPress(entity, item.id)} onPointerEnter={() => { if (dragging?.entity === entity) moveDraft(entity, dragging.id, item.id); }} onPointerUp={endLongPress}><button className="taxonomy-item-name" onClick={() => setRename({ entity, id: item.id, value: item.name })} type="button">{entity === "folder" && (item as Folder).is_locked ? "🔒 " : ""}{item.name}</button><button aria-label={`移除 ${item.name}`} className="taxonomy-delete" onClick={() => removeDraft(entity, item.id)} type="button">×</button></article>)}{!source.length && <p className="manager-empty">尚未建立項目。</p>}</div>; }
  const renameDialog = rename && <ModalDialog className="mobile-sheet-dialog" onClose={() => setRename(null)} open title={`修改${rename.entity === "category" ? "類別" : "資料夾"}`}><form className="collection-category-dialog" onSubmit={(event) => { event.preventDefault(); if (rename.value.trim()) renameDraft(rename.entity, rename.id, rename.value); }}><label>名稱<input autoFocus maxLength={80} onChange={(event) => setRename((current) => current ? { ...current, value: event.target.value } : current)} value={rename.value} /></label><div className="dialog-actions"><button className="secondary-button" onClick={() => setRename(null)} type="button">取消</button><button className="button" type="submit">套用</button></div></form></ModalDialog>;
  return <>
    <div className="bookmark-view-tabs collection-view-tabs" role="tablist"><div className="bookmark-view-tabs-scroll"><button aria-selected={view === "all"} className={view === "all" ? "active" : ""} onClick={() => select("all")} role="tab" type="button">未整理 <span>{unorganizedCount}</span></button>{sorted(localFolders.filter((item) => item.is_visible)).map((item) => <button aria-selected={view === `folder:${item.id}`} className={view === `folder:${item.id}` ? "active" : ""} key={item.id} onClick={() => select(`folder:${item.id}`, item)} role="tab" type="button">{item.is_locked ? "🔒 " : ""}{item.name} <span>{countFolder(item.id)}</span></button>)}<button aria-label="更多資料夾" className="collection-category-utility" onClick={() => { setError(null); setDialog("folder-more"); }} type="button">更多</button><button aria-label="修改資料夾" className="collection-category-utility" onClick={() => openManager("folder")} type="button">🔧</button><button aria-label="新增資料夾" className="collection-category-utility collection-category-add" onClick={() => { setError(null); setDialog("folder-add"); }} type="button">＋</button><button aria-selected={view === "trash"} className={view === "trash" ? "active trash-tab" : "trash-tab"} onClick={() => select("trash")} role="tab" type="button">垃圾桶 <span>{trashCount}</span></button></div></div>
    <div className="category-strip collection-category-strip" role="tablist"><button aria-selected={category === "all"} className={category === "all" ? "active" : ""} onClick={() => setCategory("all")} role="tab" type="button">全部 <span>{scopeItems.length}</span></button><button aria-selected={category === "unclassified"} className={category === "unclassified" ? "active" : ""} onClick={() => setCategory("unclassified")} role="tab" type="button">未分類 <span>{scopeItems.filter((item) => !item.category).length}</span></button>{scopeCategories.map((item) => <button aria-selected={category === item.id} className={category === item.id ? "active" : ""} key={item.id} onClick={() => setCategory(item.id)} role="tab" type="button">{item.name} <span>{countCategory(item.id)}</span></button>)}<button aria-label="查看更多類別" className="collection-category-utility" onClick={() => { setError(null); setDialog("category-more"); }} type="button">更多</button><button aria-label="修改類別" className="collection-category-utility" onClick={() => openManager("category")} type="button">🔧</button><button aria-label="新增類別" className="collection-category-utility collection-category-add" onClick={() => { setError(null); setDialog("category-add"); }} type="button">＋</button></div>
    <ModalDialog className="mobile-sheet-dialog" onClose={close} open={dialog === "category-add"} pending={pending} title="新增類別"><form className="collection-category-dialog" onSubmit={addCategory}><p>{folderId ? "這個類別只會顯示於目前資料夾。" : "這個類別只會顯示於未整理。"}</p><label>類別名稱<input autoFocus disabled={pending} maxLength={80} onChange={(event) => setName(event.target.value)} placeholder="例如：動畫、工作" value={name} /></label>{error && <p className="notice error">{error}</p>}<div className="dialog-actions"><button className="secondary-button" disabled={pending} onClick={close} type="button">取消</button><button className="button" disabled={pending || !name.trim()} type="submit">新增類別</button></div></form></ModalDialog>
    <ModalDialog className="mobile-sheet-dialog" onClose={close} open={dialog === "category-more"} title="目前類別"><div className="collection-category-dialog collection-category-manager"><input aria-label="搜尋類別" onChange={(event) => setQuery(event.target.value)} placeholder="搜尋類別" value={query} /><div className="collection-category-manager-list"><button className={category === "all" ? "active" : ""} onClick={() => { setCategory("all"); close(); }} type="button">全部</button><button className={category === "unclassified" ? "active" : ""} onClick={() => { setCategory("unclassified"); close(); }} type="button">未分類</button>{visibleCategories.map((item) => <button className={category === item.id ? "active" : ""} key={item.id} onClick={() => { setCategory(item.id); close(); }} type="button">{item.name}</button>)}</div></div></ModalDialog>
    <ModalDialog className="mobile-sheet-dialog" onClose={() => closeManager("category")} open={dialog === "category-edit"} pending={pending} title="修改目前類別"><div className="collection-category-dialog collection-category-manager"><p>長按後拖到另一個類別上調整位置；刪除會先在這裡隱藏，關閉後才一次儲存。</p>{error && <p className="notice error">{error}</p>}{managerItems("category")}</div></ModalDialog>
    <ModalDialog className="mobile-sheet-dialog" onClose={close} open={dialog === "folder-add"} pending={pending} title="新增資料夾"><form className="collection-category-dialog" onSubmit={addFolder}><label>資料夾名稱<input autoFocus disabled={pending} maxLength={80} onChange={(event) => setName(event.target.value)} placeholder="例如：專案、學校" value={name} /></label>{error && <p className="notice error">{error}</p>}<div className="dialog-actions"><button className="secondary-button" disabled={pending} onClick={close} type="button">取消</button><button className="button" disabled={pending || !name.trim()} type="submit">新增資料夾</button></div></form></ModalDialog>
    <ModalDialog className="mobile-sheet-dialog" onClose={close} open={dialog === "folder-more"} title="資料夾"><div className="collection-category-dialog collection-category-manager"><input aria-label="搜尋資料夾" onChange={(event) => setQuery(event.target.value)} placeholder="搜尋資料夾" value={query} /><div className="collection-category-manager-list"><button className={view === "all" ? "active" : ""} onClick={() => { select("all"); close(); }} type="button">未整理</button>{localFolders.filter((item) => item.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).map((item) => <button className={view === `folder:${item.id}` ? "active" : ""} key={item.id} onClick={() => { select(`folder:${item.id}`, item); close(); }} type="button">{item.is_locked ? "🔒 " : ""}{item.name} <span>{countFolder(item.id)}</span></button>)}</div></div></ModalDialog>
    <ModalDialog className="mobile-sheet-dialog" onClose={() => closeManager("folder")} open={dialog === "folder-edit"} pending={pending} title="修改資料夾"><div className="collection-category-dialog collection-category-manager"><p>長按後拖到另一個資料夾上調整位置；資料夾 PIN 鎖定設定已集中至安全中心。</p>{error && <p className="notice error">{error}</p>}{managerItems("folder")}</div></ModalDialog>
    {renameDialog}{pending && <OperationStatus label="正在更新整理方式…" />}<FolderUnlockDialog folder={lockedFolder} kind={kind as FolderLockKind} onClose={() => setLockedFolder(null)} onUnlocked={() => { if (lockedFolder) window.sessionStorage.setItem(`${storageKey}:unlock-target`, lockedFolder.id); window.location.reload(); }} />
  </>;
}
