"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { FolderUnlockDialog } from "@/components/content/folder-unlock-dialog";
import { ModalDialog, OperationStatus } from "@/components/ui/modal-dialog";
import type { FolderLockKind, FolderLockMode } from "@/lib/folder-locks/types";

export type CollectionView = "all" | "favorite" | "pinned" | "archived" | "trash" | `folder:${string}`;
export type CollectionCategory = "all" | "unclassified" | string;
type ContentKind = "bookmark" | "note" | "code" | "file" | "photo";
type Item = { category: { id: string } | null; folder: { id: string } | null; favorite: boolean; pinned: boolean; archived: boolean; deletedAt: string | null };
type Folder = { id: string; name: string; sort_order?: number; is_visible: boolean; is_locked?: boolean; lock_mode?: FolderLockMode | null };
type Category = { id: string; name: string; sort_order?: number; folder_id: string | null };

function contentKind(key: string): ContentKind { return key.includes(":note:") ? "note" : key.includes(":code:") ? "code" : key.includes(":file:") ? "file" : key.includes(":photo:") ? "photo" : "bookmark"; }
function sorted<T extends { name: string; sort_order?: number }>(items: T[]) { return [...items].sort((a, b) => (a.sort_order ?? 0) - (b.sort_order ?? 0) || a.name.localeCompare(b.name, "zh-Hant")); }

export function CollectionNavigation({ categories, category, folders, items, setCategory, setView, storageKey, view }: { categories: Category[]; category: CollectionCategory; folders: Folder[]; items: Item[]; setCategory: (value: CollectionCategory) => void; setView: (value: CollectionView) => void; storageKey: string; view: CollectionView }) {
  const kind = contentKind(storageKey);
  const folderId = view.startsWith("folder:") ? view.slice(7) : null;
  const [localCategories, setLocalCategories] = useState(categories);
  const [localFolders, setLocalFolders] = useState(folders);
  const [lockedFolder, setLockedFolder] = useState<Folder | null>(null);
  const [dialog, setDialog] = useState<"category-add" | "category-more" | "category-edit" | "folder-add" | "folder-more" | "folder-edit" | null>(null);
  const [name, setName] = useState(""); const [query, setQuery] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  useEffect(() => { setLocalCategories(categories); }, [categories]);
  useEffect(() => { setLocalFolders(folders); }, [folders]);
  useEffect(() => { const target = window.sessionStorage.getItem(`${storageKey}:unlock-target`); if (target && localFolders.some((folder) => folder.id === target)) { window.sessionStorage.removeItem(`${storageKey}:unlock-target`); setView(`folder:${target}`); } }, [localFolders, setView, storageKey]);
  const active = items.filter((item) => !item.deletedAt && !item.archived);
  const scopeItems = folderId ? active.filter((item) => item.folder?.id === folderId) : active.filter((item) => !item.folder);
  const scopeCategories = sorted(localCategories.filter((item) => (item.folder_id ?? null) === folderId));
  const visibleCategories = scopeCategories.filter((item) => item.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  const countFolder = (id: string) => active.filter((item) => item.folder?.id === id).length;
  const countCategory = (id: string) => scopeItems.filter((item) => item.category?.id === id).length;
  const unorganizedCount = active.filter((item) => !item.folder).length;
  const trashCount = items.filter((item) => item.deletedAt).length;
  function select(next: CollectionView, folder?: Folder) { if (folder?.is_locked) { setLockedFolder(folder); return; } setCategory("all"); setView(next); }
  function close() { if (!pending) { setDialog(null); setName(""); setError(null); } }
  async function api(url: string, method: "POST" | "PATCH" | "DELETE", body: object) { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.error ?? "無法完成操作。"); return result; }
  function notify() { window.dispatchEvent(new CustomEvent("personal-vault:taxonomy-updated", { detail: kind })); }
  async function addCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!name.trim()) return; setPending(true); setError(null); try { const result = await api("/api/taxonomy", "POST", { kind: "category", contentKind: kind, folderId, name: name.trim() }); if (result.item) setLocalCategories((current) => [...current, result.item]); notify(); close(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法新增類別。"); } finally { setPending(false); } }
  async function patchCategory(item: Category, nextName?: string, sortOrder?: number) { setPending(true); setError(null); try { await api("/api/taxonomy", "PATCH", { kind: "category", contentKind: kind, id: item.id, ...(nextName === undefined ? {} : { name: nextName }), ...(sortOrder === undefined ? {} : { sortOrder }) }); setLocalCategories((current) => current.map((value) => value.id === item.id ? { ...value, ...(nextName === undefined ? {} : { name: nextName }), ...(sortOrder === undefined ? {} : { sort_order: sortOrder }) } : value)); notify(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法修改類別。"); } finally { setPending(false); } }
  async function removeCategory(item: Category) { if (!window.confirm(`確定刪除「${item.name}」？資料會改為未分類。`)) return; setPending(true); setError(null); try { await api("/api/taxonomy", "DELETE", { kind: "category", contentKind: kind, id: item.id }); setLocalCategories((current) => current.filter((value) => value.id !== item.id)); if (category === item.id) setCategory("all"); notify(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法刪除類別。"); } finally { setPending(false); } }
  async function moveCategory(item: Category, direction: -1 | 1) { const index = scopeCategories.findIndex((value) => value.id === item.id); const other = scopeCategories[index + direction]; if (!other) return; await Promise.all([patchCategory(item, undefined, other.sort_order ?? index + direction), patchCategory(other, undefined, item.sort_order ?? index)]); }
  const folderEndpoint = kind === "bookmark" ? "/api/taxonomy" : "/api/content-folders";
  const folderPayload = (payload: Record<string, unknown>) => kind === "bookmark" ? { kind: "bookmark_folder", contentKind: kind, ...payload } : { kind, ...payload };
  async function addFolder(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!name.trim()) return; setPending(true); setError(null); try { const result = await api(folderEndpoint, "POST", folderPayload({ name: name.trim() })); if (result.item) setLocalFolders((current) => [...current, result.item]); notify(); close(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法新增資料夾。"); } finally { setPending(false); } }
  async function patchFolder(item: Folder, nextName?: string, sortOrder?: number) { setPending(true); setError(null); try { await api(folderEndpoint, "PATCH", folderPayload({ id: item.id, ...(nextName === undefined ? {} : { name: nextName }), ...(sortOrder === undefined ? {} : { sortOrder }) })); setLocalFolders((current) => current.map((value) => value.id === item.id ? { ...value, ...(nextName === undefined ? {} : { name: nextName }), ...(sortOrder === undefined ? {} : { sort_order: sortOrder }) } : value)); notify(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法修改資料夾。"); } finally { setPending(false); } }
  async function removeFolder(item: Folder) { if (!window.confirm(`確定移除「${item.name}」？其中資料會回到未整理。`)) return; setPending(true); setError(null); try { await api(folderEndpoint, "DELETE", folderPayload({ id: item.id })); setLocalFolders((current) => current.filter((value) => value.id !== item.id)); if (view === `folder:${item.id}`) select("all"); notify(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法移除資料夾。"); } finally { setPending(false); } }
  async function moveFolder(item: Folder, direction: -1 | 1) { const list = sorted(localFolders); const index = list.findIndex((value) => value.id === item.id); const other = list[index + direction]; if (!other) return; await Promise.all([patchFolder(item, undefined, other.sort_order ?? index + direction), patchFolder(other, undefined, item.sort_order ?? index)]); }
  const row = (item: Category | Folder, index: number, list: (Category | Folder)[], entity: "category" | "folder") => <div className="collection-manage-row" key={item.id}><button className="collection-manage-name" disabled={pending} onClick={() => { const next = window.prompt(entity === "category" ? "類別名稱" : "資料夾名稱", item.name); if (next?.trim()) void (entity === "category" ? patchCategory(item as Category, next.trim()) : patchFolder(item as Folder, next.trim())); }} type="button">{entity === "folder" && (item as Folder).is_locked ? "🔒 " : ""}{item.name}</button><div><button aria-label="上移" disabled={pending || index === 0} onClick={() => void (entity === "category" ? moveCategory(item as Category, -1) : moveFolder(item as Folder, -1))} type="button">↑</button><button aria-label="下移" disabled={pending || index === list.length - 1} onClick={() => void (entity === "category" ? moveCategory(item as Category, 1) : moveFolder(item as Folder, 1))} type="button">↓</button><button aria-label={`刪除 ${item.name}`} className="delete-button compact" disabled={pending} onClick={() => void (entity === "category" ? removeCategory(item as Category) : removeFolder(item as Folder))} type="button">×</button></div></div>;
  return <>
    <div className="bookmark-view-tabs collection-view-tabs" role="tablist"><div className="bookmark-view-tabs-scroll"><button aria-selected={view === "all"} className={view === "all" ? "active" : ""} onClick={() => select("all")} role="tab" type="button">未整理 <span>{unorganizedCount}</span></button>{sorted(localFolders.filter((item) => item.is_visible)).map((item) => <button aria-selected={view === `folder:${item.id}`} className={view === `folder:${item.id}` ? "active" : ""} key={item.id} onClick={() => select(`folder:${item.id}`, item)} type="button">{item.is_locked ? "🔒 " : ""}{item.name} <span>{countFolder(item.id)}</span></button>)}<button aria-label="更多資料夾" className="collection-category-utility" onClick={() => { setError(null); setDialog("folder-more"); }} type="button">更多</button><button aria-label="新增資料夾" className="collection-category-utility collection-category-add" onClick={() => { setError(null); setDialog("folder-add"); }} type="button">＋</button><button aria-label="修改資料夾" className="collection-category-utility" onClick={() => { setError(null); setDialog("folder-edit"); }} type="button">🔧</button><button aria-selected={view === "trash"} className={view === "trash" ? "active trash-tab" : "trash-tab"} onClick={() => select("trash")} role="tab" type="button">垃圾桶 <span>{trashCount}</span></button></div></div>
    <div className="category-strip collection-category-strip" role="tablist"><button aria-selected={category === "all"} className={category === "all" ? "active" : ""} onClick={() => setCategory("all")} role="tab" type="button">全部 <span>{scopeItems.length}</span></button><button aria-selected={category === "unclassified"} className={category === "unclassified" ? "active" : ""} onClick={() => setCategory("unclassified")} role="tab" type="button">未分類 <span>{scopeItems.filter((item) => !item.category).length}</span></button>{scopeCategories.map((item) => <button aria-selected={category === item.id} className={category === item.id ? "active" : ""} key={item.id} onClick={() => setCategory(item.id)} role="tab" type="button">{item.name} <span>{countCategory(item.id)}</span></button>)}<button aria-label="查看更多類別" className="collection-category-utility" onClick={() => { setError(null); setDialog("category-more"); }} type="button">更多</button><button aria-label="新增類別" className="collection-category-utility collection-category-add" onClick={() => { setError(null); setDialog("category-add"); }} type="button">＋</button><button aria-label="修改類別" className="collection-category-utility" onClick={() => { setError(null); setDialog("category-edit"); }} type="button">🔧</button></div>
    <ModalDialog className="mobile-sheet-dialog" onClose={close} open={dialog === "category-add"} pending={pending} title="新增類別"><form className="collection-category-dialog" onSubmit={addCategory}><p>{folderId ? "這個類別只會顯示於目前資料夾。" : "這個類別只會顯示於未整理。"}</p><label>類別名稱<input autoFocus disabled={pending} maxLength={80} onChange={(event) => setName(event.target.value)} placeholder="例如：動畫、工作" value={name} /></label>{error && <p className="notice error">{error}</p>}<div className="dialog-actions"><button className="secondary-button" disabled={pending} onClick={close} type="button">取消</button><button className="button" disabled={pending || !name.trim()} type="submit">新增類別</button></div></form></ModalDialog>
    <ModalDialog className="mobile-sheet-dialog" onClose={close} open={dialog === "category-more"} title="目前類別"><div className="collection-category-dialog collection-category-manager"><input aria-label="搜尋類別" onChange={(event) => setQuery(event.target.value)} placeholder="搜尋類別" value={query} /><div className="collection-category-manager-list"><button className={category === "all" ? "active" : ""} onClick={() => { setCategory("all"); close(); }} type="button">全部</button><button className={category === "unclassified" ? "active" : ""} onClick={() => { setCategory("unclassified"); close(); }} type="button">未分類</button>{visibleCategories.map((item) => <button className={category === item.id ? "active" : ""} key={item.id} onClick={() => { setCategory(item.id); close(); }} type="button">{item.name}</button>)}</div></div></ModalDialog>
    <ModalDialog className="mobile-sheet-dialog" onClose={close} open={dialog === "category-edit"} pending={pending} title="修改目前類別"><div className="collection-category-dialog collection-category-manager"><p>點名稱修改；↑↓ 調整位置；× 刪除。</p>{error && <p className="notice error">{error}</p>}<div className="collection-category-manager-list collection-edit-list">{scopeCategories.map((item, index) => row(item, index, scopeCategories, "category"))}{!scopeCategories.length && <p className="lead">這裡還沒有類別。</p>}</div></div></ModalDialog>
    <ModalDialog className="mobile-sheet-dialog" onClose={close} open={dialog === "folder-add"} pending={pending} title="新增資料夾"><form className="collection-category-dialog" onSubmit={addFolder}><label>資料夾名稱<input autoFocus disabled={pending} maxLength={80} onChange={(event) => setName(event.target.value)} placeholder="例如：專案、學校" value={name} /></label>{error && <p className="notice error">{error}</p>}<div className="dialog-actions"><button className="secondary-button" disabled={pending} onClick={close} type="button">取消</button><button className="button" disabled={pending || !name.trim()} type="submit">新增資料夾</button></div></form></ModalDialog>
    <ModalDialog className="mobile-sheet-dialog" onClose={close} open={dialog === "folder-more"} title="資料夾"><div className="collection-category-dialog collection-category-manager"><input aria-label="搜尋資料夾" onChange={(event) => setQuery(event.target.value)} placeholder="搜尋資料夾" value={query} /><div className="collection-category-manager-list"><button className={view === "all" ? "active" : ""} onClick={() => { select("all"); close(); }} type="button">未整理</button>{localFolders.filter((item) => item.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).map((item) => <button className={view === `folder:${item.id}` ? "active" : ""} key={item.id} onClick={() => { select(`folder:${item.id}`, item); close(); }} type="button">{item.is_locked ? "🔒 " : ""}{item.name} <span>{countFolder(item.id)}</span></button>)}</div></div></ModalDialog>
    <ModalDialog className="mobile-sheet-dialog" onClose={close} open={dialog === "folder-edit"} pending={pending} title="修改資料夾"><div className="collection-category-dialog collection-category-manager"><p>點名稱修改；資料夾 PIN 鎖定設定已集中至安全中心。</p>{error && <p className="notice error">{error}</p>}<div className="collection-category-manager-list collection-edit-list">{sorted(localFolders).map((item, index, list) => row(item, index, list, "folder"))}{!localFolders.length && <p className="lead">尚未建立資料夾。</p>}</div><a className="secondary-button collection-category-manage-link" href="/security">前往安全中心設定資料夾 PIN</a></div></ModalDialog>
    {pending && <OperationStatus label="正在更新整理方式…" />}
    <FolderUnlockDialog folder={lockedFolder} kind={kind as FolderLockKind} onClose={() => setLockedFolder(null)} onUnlocked={() => { if (lockedFolder) window.sessionStorage.setItem(`${storageKey}:unlock-target`, lockedFolder.id); window.location.reload(); }} />
  </>;
}
