"use client";

import { FormEvent, useState } from "react";

type Folder = { id: string; name: string; is_visible: boolean };
type Kind = "note" | "code" | "file";

export function ContentFolderManager({ folders, kind, onChanged }: { folders: Folder[]; kind: Kind; onChanged: () => Promise<void> }) {
  const [name, setName] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [value, setValue] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function request(method: "POST" | "PATCH" | "DELETE", body: object) { setPending(true); setError(null); try { const response = await fetch("/api/content-folders", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, ...body }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error ?? "操作失敗。"); await onChanged(); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "操作失敗。"); return false; } finally { setPending(false); } }
  async function add(event: FormEvent) { event.preventDefault(); if (!name.trim()) return; if (await request("POST", { name: name.trim() })) setName(""); }
  return <section className="category-manager"><header className="manager-heading"><p className="eyebrow">CONTENT FOLDERS</p><h2>管理資料夾</h2><p>資料夾會立即同步到新增與修改的收藏設定；移除資料夾不會刪除內容。</p></header>{error && <p className="notice error">{error}</p>}<form className="category-create-row" onSubmit={add}><input onChange={(event) => setName(event.target.value)} placeholder="例如：專案、學習、待整理" value={name} /><button className="button compact" disabled={pending} type="submit">＋ 新增資料夾</button></form><div className="folder-list">{folders.length ? folders.map((folder) => <article className="folder-row" key={folder.id}><div>{editing === folder.id ? <input autoFocus onChange={(event) => setValue(event.target.value)} value={value} /> : <><strong>{folder.name}</strong><small>{folder.is_visible ? "顯示於清單與選單" : "已隱藏於清單與選單"}</small></>}</div><div className="manager-actions">{editing === folder.id ? <><button className="button compact" disabled={pending} onClick={() => { if (value.trim()) void request("PATCH", { id: folder.id, name: value.trim() }).then((ok) => ok && setEditing(null)); }} type="button">儲存</button><button className="secondary-button compact" disabled={pending} onClick={() => setEditing(null)} type="button">取消</button></> : <><button className="secondary-button compact" disabled={pending} onClick={() => void request("PATCH", { id: folder.id, visible: !folder.is_visible })} type="button">{folder.is_visible ? "隱藏" : "顯示"}</button><button className="secondary-button compact" disabled={pending} onClick={() => { setEditing(folder.id); setValue(folder.name); }} type="button">修改</button><button className="delete-button compact" disabled={pending} onClick={() => void request("DELETE", { id: folder.id })} type="button">移除</button></>}</div></article>) : <p className="manager-empty">尚未建立資料夾。</p>}</div></section>;
}
