"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { CollectionCategory, CollectionNavigation, CollectionView } from "@/components/content/collection-navigation";
import { CoverImageField, type CoverSelection, uploadCover } from "@/components/content/cover-image-field";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { ModalDialog, OperationStatus } from "@/components/ui/modal-dialog";
import type { Note, NotesWorkspaceData } from "@/lib/notes/types";

function CollectionSettings({ folders, note }: { folders: NotesWorkspaceData["folders"]; note?: Note }) {
  return <details className="collection-settings"><summary>收藏設定 <small>可複選</small></summary><div className="collection-settings-menu"><label><input defaultChecked={note?.favorite} name="favorite" type="checkbox" /> 我的最愛</label><label><input defaultChecked={note?.pinned} name="pinned" type="checkbox" /> 置頂</label><label><input defaultChecked={note?.archived} name="archived" type="checkbox" /> 封存</label><div className="collection-settings-divider" /><span>資料夾（選擇一個）</span><label><input defaultChecked={!note?.folder} name="contentFolderId" type="radio" value="" /> 不放入資料夾</label>{folders.filter((folder) => folder.is_visible || folder.id === note?.folder?.id).map((folder) => <label key={folder.id}><input defaultChecked={folder.id === note?.folder?.id} name="contentFolderId" type="radio" value={folder.id} /> {folder.name}{folder.is_visible ? "" : "（已隱藏）"}</label>)}</div></details>;
}

export function NotesWorkspace({ initialData, createMode = false }: { initialData: NotesWorkspaceData; createMode?: boolean }) {
  const router = useRouter();
  const [data, setData] = useState(initialData); const [view, setView] = useState<CollectionView>("all"); const [category, setCategory] = useState<CollectionCategory>("all"); const [query, setQuery] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const [selected, setSelected] = useState<Note | null>(null); const [editing, setEditing] = useState<Note | null>(null); const [confirm, setConfirm] = useState<{ note: Note; permanent: boolean } | null>(null); const [cover, setCover] = useState<CoverSelection>(null);
  const load = useCallback(async () => { const response = await fetch("/api/notes", { cache: "no-store" }); if (!response.ok) { setError("目前無法讀取筆記。"); return; } setData(await response.json() as NotesWorkspaceData); }, []);
  useEffect(() => { if (createMode) void load(); }, [createMode, load]);
  const notes = useMemo(() => data.notes.filter((note) => { if (view === "trash" ? !note.deletedAt : Boolean(note.deletedAt)) return false; if (view === "all" && note.archived) return false; if (view === "favorite" && (!note.favorite || note.archived)) return false; if (view === "pinned" && (!note.pinned || note.archived)) return false; if (view === "archived" && !note.archived) return false; if (view.startsWith("folder:") && note.folder?.id !== view.slice(7)) return false; if (category === "unclassified" && note.category) return false; if (category !== "all" && category !== "unclassified" && note.category?.id !== category) return false; return `${note.title} ${note.description ?? ""} ${note.content}`.toLowerCase().includes(query.toLowerCase()); }), [category, data.notes, query, view]);
  async function save(event: FormEvent<HTMLFormElement>, note?: Note) { event.preventDefault(); setPending(true); setError(null); try { const form = new FormData(event.currentTarget); const coverTicket = await uploadCover(cover); const body = { ...(note ? { id: note.id } : {}), title: form.get("title"), description: form.get("description"), content: form.get("content"), categoryId: form.get("categoryId") || null, contentFolderId: form.get("contentFolderId") || null, favorite: form.get("favorite") === "on", pinned: form.get("pinned") === "on", archived: form.get("archived") === "on", coverTicket, tags: [] as string[] }; const response = await fetch("/api/notes", { method: note ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.error ?? "無法儲存筆記。"); if (!note && createMode) { router.replace("/notes"); router.refresh(); return; } setEditing(null); setSelected(null); setCover(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法儲存筆記。"); } finally { setPending(false); } }
  async function action(note: Note, actionName: "trash" | "restore") { setPending(true); setError(null); try { const response = await fetch("/api/notes", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: note.id, action: actionName }) }); if (!response.ok) throw new Error(); setSelected(null); await load(); } catch { setError("無法更新筆記狀態。"); } finally { setPending(false); } }
  async function remove() { if (!confirm) return; setPending(true); setError(null); try { const response = await fetch("/api/notes", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: confirm.note.id }) }); if (!response.ok) throw new Error(); setConfirm(null); setSelected(null); await load(); } catch { setError("無法永久刪除筆記。"); } finally { setPending(false); } }
  const editor = (note?: Note) => <form className="note-editor" onSubmit={(event) => void save(event, note)}><label>標題<input defaultValue={note?.title ?? ""} name="title" required /></label><label>摘要<textarea defaultValue={note?.description ?? ""} name="description" placeholder="摘要（選填）" rows={2} /></label><label>內容<textarea defaultValue={note?.content ?? ""} name="content" placeholder="開始輸入筆記內容…" required rows={14} /></label><label>類別<select defaultValue={note?.category?.id ?? ""} name="categoryId"><option value="">未分類</option>{data.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><CollectionSettings folders={data.folders} note={note} /><CoverImageField initialUrl={note?.coverImageUrl} onChange={setCover} /><div className="dialog-actions"><button className="button" disabled={pending} type="submit">{pending ? "儲存中…" : note ? "儲存修改" : "儲存筆記"}</button>{note && <button className="secondary-button" onClick={() => setEditing(null)} type="button">取消</button>}</div></form>;
  if (createMode) return <section className="notes-workspace create-only">{pending && <OperationStatus label="正在儲存筆記…" />}{error && <p className="notice error" role="alert">{error}</p>}{editor()}</section>;
  return <section className="library-workspace">{pending && <OperationStatus label="正在處理筆記…" />}{error && <p className="notice error" role="alert">{error}</p>}<div className="library-heading"><div><p className="eyebrow">PRIVATE NOTES</p><h2>筆記</h2></div></div><CollectionNavigation categories={data.categories} category={category} folders={data.folders} items={data.notes} setCategory={setCategory} setView={setView} storageKey="personal-vault:note-system-folders:v1" view={view} /><input aria-label="搜尋筆記" className="note-search" onChange={(event) => setQuery(event.target.value)} placeholder="搜尋筆記標題或內容" value={query} /><div className="content-item-list">{notes.map((note) => <article className="content-item-card" key={note.id}><button className="content-item-open" onClick={() => setSelected(note)} type="button">{note.coverImageUrl ? <img alt="" src={note.coverImageUrl} /> : <span className="content-cover-placeholder">筆記</span>}<div><p className="bookmark-meta">{note.category?.name ?? "未分類"}{note.folder && ` · ${note.folder.name}`}</p><h3>{note.title}</h3><p>{note.description || note.content.slice(0, 90)}</p></div></button></article>)}{notes.length === 0 && <p className="lead">此清單尚無筆記。</p>}</div><ModalDialog onClose={() => setSelected(null)} open={Boolean(selected)} pending={pending} title={selected?.title ?? "筆記內容"}>{selected && <><p className="detail-content">{selected.content}</p><div className="dialog-actions">{selected.deletedAt ? <><button className="button" onClick={() => void action(selected, "restore")} type="button">還原</button><button className="delete-button" onClick={() => setConfirm({ note: selected, permanent: true })} type="button">永久刪除</button></> : <><button className="secondary-button" onClick={() => { setEditing(selected); setSelected(null); }} type="button">修改</button><button className="delete-button" onClick={() => setConfirm({ note: selected, permanent: false })} type="button">刪除</button></>}</div></>}</ModalDialog><ModalDialog onClose={() => setEditing(null)} open={Boolean(editing)} pending={pending} title="修改筆記">{editing && editor(editing)}</ModalDialog><ConfirmDialog confirmLabel={confirm?.permanent ? "永久刪除" : "移至垃圾桶"} description={confirm?.permanent ? "此筆記會永久刪除，無法還原。" : "此筆記會保留在垃圾桶 30 天，期間可隨時還原。"} error={error} onCancel={() => setConfirm(null)} onConfirm={() => { if (confirm) { if (confirm.permanent) void remove(); else { void action(confirm.note, "trash"); setConfirm(null); } } }} open={Boolean(confirm)} pending={pending} title={confirm?.permanent ? "永久刪除筆記？" : "移至垃圾桶？"} /></section>;
}
