"use client";

import Link from "next/link";
import { FormEvent, useCallback, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import type { Note, NotesWorkspaceData } from "@/lib/notes/types";

export function NotesWorkspace({ initialData, createMode = false }: { initialData: NotesWorkspaceData; createMode?: boolean }) {
  const router = useRouter(); const [data, setData] = useState(initialData); const [query, setQuery] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const [selected, setSelected] = useState<Note | null>(null); const [editing, setEditing] = useState<Note | null>(null); const [deleting, setDeleting] = useState<Note | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/notes", { cache: "no-store" }); if (!response.ok) { setError("目前無法讀取筆記。"); return; } setData(await response.json() as NotesWorkspaceData); }, []);
  const list = useMemo(() => data.notes.filter((note) => `${note.title} ${note.description ?? ""}`.toLowerCase().includes(query.toLowerCase())), [data.notes, query]);
  function body(form: FormData, id?: string) { return { ...(id ? { id } : {}), title: form.get("title"), description: form.get("description"), content: form.get("content"), categoryId: form.get("categoryId") || null, tags: String(form.get("tags") ?? "").split(",").map((tag) => tag.trim()).filter(Boolean) }; }
  async function save(event: FormEvent<HTMLFormElement>, id?: string) { event.preventDefault(); setPending(true); const response = await fetch("/api/notes", { method: id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body(new FormData(event.currentTarget), id)) }); setPending(false); if (!response.ok) { setError("無法儲存筆記。"); return; } if (!id) { router.replace("/notes"); router.refresh(); return; } setEditing(null); setSelected(null); await load(); }
  async function remove() { if (!deleting) return; setPending(true); setError(null); const response = await fetch("/api/notes", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: deleting.id }) }); setPending(false); if (!response.ok) { setError("無法刪除筆記。"); return; } setSelected(null); setDeleting(null); setData((current) => ({ ...current, notes: current.notes.filter((note) => note.id !== deleting.id) })); }
  const editor = (note?: Note) => <form className="note-editor" onSubmit={(event) => void save(event, note?.id)}><input defaultValue={note?.title ?? ""} name="title" placeholder="筆記標題" required /><textarea defaultValue={note?.description ?? ""} name="description" placeholder="摘要（選填）" rows={2} /><textarea defaultValue={note?.content ?? ""} name="content" placeholder="開始輸入筆記內容…" required rows={14} /><div className="note-editor-meta"><select defaultValue={note?.category?.id ?? ""} name="categoryId"><option value="">未分類</option>{data.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input defaultValue={note?.tags.map((tag) => tag.name).join(", ") ?? ""} name="tags" placeholder="標籤，以逗號分隔" /></div><div className="dialog-actions"><button className="button" disabled={pending} type="submit">{pending ? "儲存中…" : note ? "儲存修改" : "儲存筆記"}</button>{note && <button className="secondary-button" onClick={() => setEditing(null)} type="button">取消</button>}</div></form>;
  if (createMode) return <section className="notes-workspace create-only">{error && <p className="notice error">{error}</p>}{editor()}</section>;
  return <section className="library-workspace">{error && <p className="notice error" role="alert">{error}</p>}<div className="library-heading"><div><p className="eyebrow">PRIVATE NOTES</p><h2>筆記</h2></div><Link className="button compact" href="/create/note">＋ 新增資料</Link></div><input aria-label="搜尋筆記" className="note-search" onChange={(event) => setQuery(event.target.value)} placeholder="搜尋筆記標題" value={query} /><div className="library-list">{list.map((note) => <article className="library-card note-list-card" key={note.id}><button className="library-open" onClick={() => setSelected(note)} type="button"><p className="bookmark-meta">{note.category?.name ?? "未分類"}</p><h3>{note.title}</h3></button><div className="center-actions"><button className="secondary-button" onClick={() => setEditing(note)} type="button">修改</button><button className="delete-button" onClick={() => setDeleting(note)} type="button">刪除</button></div></article>)}{list.length === 0 && <p className="lead">尚無筆記。</p>}</div>{selected && <section aria-modal="true" className="inline-dialog detail-dialog" role="dialog"><h2>{selected.title}</h2><p className="detail-content">{selected.content}</p><div className="dialog-actions"><button className="secondary-button" onClick={() => setSelected(null)} type="button">關閉</button></div></section>}{editing && <section aria-modal="true" className="inline-dialog edit-dialog" role="dialog"><h2>修改筆記</h2>{editor(editing)}</section>}<ConfirmDialog description={`「${deleting?.title ?? ""}」將永久刪除，無法還原。`} error={error} onCancel={() => setDeleting(null)} onConfirm={() => { void remove(); }} open={Boolean(deleting)} pending={pending} title="刪除筆記？" /></section>;
}
