"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { ModalDialog } from "@/components/ui/modal-dialog";
import { ResponsiveChipOverflow } from "@/components/ui/responsive-chip-overflow";

type VaultStatus = { initialized: boolean; salt?: string; wrappedVaultKey?: string; wrappedKeyNonce?: string; kdfParameters?: { algorithm: "PBKDF2"; hash: "SHA-256"; iterations: number; keyLength: 256 } };
type CipherItem = { id: string; ciphertext: string; nonce: string; aad: { entryId: string; version: 1 }; categoryId: string | null };
type PlainItem = { id: string; label: string; username: string; secret: string; notes: string; categoryId: string | null };
type VaultCategory = { id: string; name: string; sortOrder: number; itemCount: number };

const encoder = new TextEncoder();
const decoder = new TextDecoder();
const iterations = 600_000;
const toBase64 = (bytes: ArrayBuffer | Uint8Array) => { const data = new Uint8Array(bytes); let binary = ""; data.forEach((byte) => { binary += String.fromCharCode(byte); }); return btoa(binary); };
const fromBase64 = (value: string) => Uint8Array.from(atob(value), (char) => char.charCodeAt(0));
const asArrayBuffer = (bytes: Uint8Array) => bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
const randomBytes = (length: number) => crypto.getRandomValues(new Uint8Array(length));
const maskedSecret = (value: string) => "•".repeat(Math.min(Math.max(value.length, 8), 24));

async function deriveKey(password: string, salt: Uint8Array, count: number) {
  const material = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveKey"]);
  return crypto.subtle.deriveKey({ name: "PBKDF2", hash: "SHA-256", salt: asArrayBuffer(salt), iterations: count }, material, { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]);
}

function VaultGate({ creating, error, pending, onSubmit }: { creating: boolean; error: string | null; pending: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  return <section className="vault-gate">
    <div className="vault-gate-form">
      <p className="eyebrow">ZERO-KNOWLEDGE VAULT</p><h2>{creating ? "建立 Vault 密碼" : "解鎖保管庫"}</h2>
      <p>{creating ? "此密碼只在這台裝置的瀏覽器中使用來解鎖資料；我們無法替你重設，請妥善保管。" : "金鑰只會保存在此頁面的記憶體中，閒置 10 分鐘會自動鎖定。"}</p>
      {error && <p className="notice error" role="alert">{error}</p>}
      <form className="form" onSubmit={onSubmit}>
        <div className="field"><label>Vault 密碼</label><input autoComplete={creating ? "new-password" : "current-password"} minLength={creating ? 11 : undefined} name="password" required type="password" /></div>
        {creating && <div className="field"><label>再次輸入 Vault 密碼</label><input autoComplete="new-password" minLength={11} name="confirmation" required type="password" /></div>}
        <button className="button" disabled={pending} type="submit">{pending ? (creating ? "建立中…" : "解鎖中…") : (creating ? "建立加密保管庫" : "解鎖 Vault")}</button>
      </form>
    </div>
    <aside className="vault-gate-security" aria-label="保管庫安全資訊"><strong>你的資料如何被保護</strong><ul><li><b>AES-256-GCM</b><span>敏感內容在瀏覽器端加密。</span></li><li><b>Zero-Knowledge</b><span>伺服器不會取得 Vault 密碼或明文。</span></li><li><b>自動鎖定</b><span>閒置 10 分鐘後清除記憶體中的金鑰。</span></li></ul></aside>
  </section>;
}

export function VaultWorkspace() {
  const [status, setStatus] = useState<VaultStatus | null>(null); const [vaultKey, setVaultKey] = useState<CryptoKey | null>(null); const [items, setItems] = useState<PlainItem[]>([]); const [categories, setCategories] = useState<VaultCategory[]>([]); const [visibleItemIds, setVisibleItemIds] = useState<Set<string>>(() => new Set()); const [selectedItemIds, setSelectedItemIds] = useState<Set<string>>(() => new Set()); const [selectionMode, setSelectionMode] = useState(false); const [batchMoveOpen, setBatchMoveOpen] = useState(false); const [batchCategoryId, setBatchCategoryId] = useState("unclassified"); const [batchDeleteOpen, setBatchDeleteOpen] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [pending, setPending] = useState(false); const [deleting, setDeleting] = useState<PlainItem | null>(null); const [editing, setEditing] = useState<PlainItem | null>(null); const [itemDialogOpen, setItemDialogOpen] = useState(false); const [menuItemId, setMenuItemId] = useState<string | null>(null); const [query, setQuery] = useState(""); const [categoryFilter, setCategoryFilter] = useState<string | "all" | "unclassified">("all"); const [categoryMoreOpen, setCategoryMoreOpen] = useState(false); const [categoryAddOpen, setCategoryAddOpen] = useState(false); const [categoryName, setCategoryName] = useState(""); const [categoryManagerOpen, setCategoryManagerOpen] = useState(false); const [categoryDraft, setCategoryDraft] = useState<VaultCategory[]>([]); const [deletingCategory, setDeletingCategory] = useState<VaultCategory | null>(null); const [reassignCategoryId, setReassignCategoryId] = useState<string>("unclassified"); const activityTimer = useRef<number | null>(null);
  const lock = useCallback(() => { setVaultKey(null); setItems([]); setCategories([]); setVisibleItemIds(new Set()); setSelectedItemIds(new Set()); setSelectionMode(false); setItemDialogOpen(false); setMenuItemId(null); setError(null); setNotice(null); }, []);
  const fetchStatus = useCallback(async () => { const response = await fetch("/api/vault", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法讀取保管庫。"); return data as VaultStatus; }, []);
  const loadCategories = useCallback(async () => { const response = await fetch("/api/vault/categories", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法讀取分類。"); setCategories(data.categories as VaultCategory[]); }, []);
  useEffect(() => { let cancelled = false; void fetchStatus().then((data) => { if (!cancelled) setStatus(data); }).catch((cause) => { if (!cancelled) setError(cause.message); }); return () => { cancelled = true; }; }, [fetchStatus]);
  useEffect(() => { if (!vaultKey) return; const reset = () => { if (activityTimer.current) window.clearTimeout(activityTimer.current); activityTimer.current = window.setTimeout(lock, 10 * 60 * 1000); }; reset(); window.addEventListener("pointerdown", reset); window.addEventListener("keydown", reset); return () => { if (activityTimer.current) window.clearTimeout(activityTimer.current); window.removeEventListener("pointerdown", reset); window.removeEventListener("keydown", reset); }; }, [vaultKey, lock]);
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(null), 3000); return () => window.clearTimeout(timer); }, [notice]);

  async function decryptItems(key: CryptoKey) { const response = await fetch("/api/vault/items", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法讀取加密項目。"); const decrypted = await Promise.all((data.items as CipherItem[]).map(async (item) => { const plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64(item.nonce), additionalData: encoder.encode(JSON.stringify(item.aad)) }, key, fromBase64(item.ciphertext)); return { id: item.id, categoryId: item.categoryId ?? null, ...JSON.parse(decoder.decode(plain)) } as PlainItem; })); setItems(decrypted); }
  async function initialize(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get("password") ?? ""); const confirmation = String(form.get("confirmation") ?? ""); if (password.length < 11 || password !== confirmation) { setError("請設定至少 11 字元且兩次相同的 Vault 密碼。"); return; } setPending(true); setError(null); try { const salt = randomBytes(16); const wrappingNonce = randomBytes(12); const wrappingKey = await deriveKey(password, salt, iterations); const generated = await crypto.subtle.generateKey({ name: "AES-GCM", length: 256 }, true, ["encrypt", "decrypt"]); const rawVaultKey = await crypto.subtle.exportKey("raw", generated); const wrappedVaultKey = await crypto.subtle.encrypt({ name: "AES-GCM", iv: wrappingNonce, additionalData: encoder.encode("personal-vault-key:v1") }, wrappingKey, rawVaultKey); const response = await fetch("/api/vault", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ salt: toBase64(salt), wrappedVaultKey: toBase64(wrappedVaultKey), wrappedKeyNonce: toBase64(wrappingNonce), kdfParameters: { algorithm: "PBKDF2", hash: "SHA-256", iterations, keyLength: 256 } }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法建立保管庫。"); const key = await crypto.subtle.importKey("raw", rawVaultKey, { name: "AES-GCM" }, false, ["encrypt", "decrypt"]); setVaultKey(key); setStatus(await fetchStatus()); await loadCategories(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法建立保管庫。"); } finally { setPending(false); } }
  async function unlock(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!status?.initialized || !status.salt || !status.wrappedVaultKey || !status.wrappedKeyNonce || !status.kdfParameters) return; const password = String(new FormData(event.currentTarget).get("password") ?? ""); setPending(true); setError(null); try { const wrappingKey = await deriveKey(password, fromBase64(status.salt), status.kdfParameters.iterations); const raw = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64(status.wrappedKeyNonce), additionalData: encoder.encode("personal-vault-key:v1") }, wrappingKey, fromBase64(status.wrappedVaultKey)); const key = await crypto.subtle.importKey("raw", raw, { name: "AES-GCM" }, false, ["encrypt", "decrypt"]); await Promise.all([decryptItems(key), loadCategories()]); setVaultKey(key); } catch { setError("Vault 密碼錯誤，或加密資料無法驗證。"); } finally { setPending(false); } }
  function closeItemDialog() { if (!pending) { setItemDialogOpen(false); setEditing(null); } }
  async function saveItem(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!vaultKey) return; const form = new FormData(event.currentTarget); const id = editing?.id ?? crypto.randomUUID(); const aad = { entryId: id, version: 1 as const }; const value = { label: String(form.get("label") ?? "").trim(), username: String(form.get("username") ?? "").trim(), secret: String(form.get("secret") ?? ""), notes: String(form.get("notes") ?? "").trim() }; const rawCategoryId = String(form.get("categoryId") ?? ""); const categoryId = rawCategoryId || null; if (!value.label || !value.secret) { setError("請填寫項目名稱與敏感內容。"); return; } setPending(true); setError(null); try { const nonce = randomBytes(12); const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv: nonce, additionalData: encoder.encode(JSON.stringify(aad)) }, vaultKey, encoder.encode(JSON.stringify(value))); const response = await fetch("/api/vault/items", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, ciphertext: toBase64(ciphertext), nonce: toBase64(nonce), aad, categoryId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法儲存項目。"); await Promise.all([decryptItems(vaultKey), loadCategories()]); setMenuItemId(null); setItemDialogOpen(false); setEditing(null); setNotice(editing ? "已重新加密並更新保管項目。" : "已加密儲存保管項目。"); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法儲存項目。"); } finally { setPending(false); } }
  async function copySecret(item: PlainItem) { try { await navigator.clipboard.writeText(item.secret); setNotice(`已複製「${item.label}」的敏感內容。`); } catch { setError("無法複製敏感內容，請確認瀏覽器允許剪貼簿權限。"); } }
  async function remove() { if (!deleting) return; setPending(true); setError(null); try { const response = await fetch("/api/vault/items", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: deleting.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法刪除項目。"); setDeleting(null); setMenuItemId(null); setItems((current) => current.filter((item) => item.id !== deleting.id)); await loadCategories(); setNotice("已刪除保管庫項目。"); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法刪除項目。"); } finally { setPending(false); } }
  function toggleItemSelection(id: string) { setSelectedItemIds((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  function closeSelectionMode() { setSelectionMode(false); setSelectedItemIds(new Set()); setBatchMoveOpen(false); setBatchDeleteOpen(false); }
  async function runBatch(action: "move" | "delete") { const ids = [...selectedItemIds]; if (!ids.length) return; setPending(true); setError(null); try { const response = await fetch("/api/vault/items/batch", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(action === "move" ? { action, ids, categoryId: batchCategoryId === "unclassified" ? null : batchCategoryId } : { action, ids }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法批量更新項目。"); const affected = new Set<string>(data.affectedIds ?? []); if (action === "move") { const categoryId = batchCategoryId === "unclassified" ? null : batchCategoryId; setItems((current) => current.map((item) => affected.has(item.id) ? { ...item, categoryId } : item)); setNotice(`已將 ${affected.size} 筆保管資料移動到指定分類。`); } else { setItems((current) => current.filter((item) => !affected.has(item.id))); setNotice(`已刪除 ${affected.size} 筆保管資料。`); } await loadCategories(); closeSelectionMode(); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法批量更新項目。"); } finally { setPending(false); } }
  async function addCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!categoryName.trim()) return; setPending(true); setError(null); try { const response = await fetch("/api/vault/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: categoryName.trim() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法新增分類。"); await loadCategories(); setCategoryName(""); setCategoryAddOpen(false); setNotice("已新增保管庫分類。"); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法新增分類。"); } finally { setPending(false); } }
  function openManager() { setError(null); setCategoryDraft(categories.map((category) => ({ ...category }))); setCategoryManagerOpen(true); }
  function moveCategory(id: string, direction: -1 | 1) { setCategoryDraft((current) => { const index = current.findIndex((category) => category.id === id); const target = index + direction; if (index < 0 || target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; }); }
  async function saveCategoryManager() { const changed = categoryDraft.some((category, index) => { const original = categories.find((value) => value.id === category.id); return !original || original.name !== category.name.trim() || original.sortOrder !== index; }); if (!changed) { setCategoryManagerOpen(false); return; } setPending(true); setError(null); try { for (const [sortOrder, category] of categoryDraft.entries()) { const original = categories.find((value) => value.id === category.id); if (!original || original.name !== category.name.trim() || original.sortOrder !== sortOrder) { const response = await fetch("/api/vault/categories", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: category.id, name: category.name.trim(), sortOrder }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法儲存分類。"); } } await loadCategories(); setCategoryManagerOpen(false); setNotice("已儲存分類整理。"); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法儲存分類整理。"); } finally { setPending(false); } }
  async function removeCategory() { if (!deletingCategory) return; setPending(true); setError(null); try { const response = await fetch("/api/vault/categories", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: deletingCategory.id, reassignToId: reassignCategoryId === "unclassified" ? null : reassignCategoryId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法刪除分類。"); await Promise.all([loadCategories(), vaultKey ? decryptItems(vaultKey) : Promise.resolve()]); setCategoryDraft((current) => current.filter((category) => category.id !== deletingCategory.id)); if (categoryFilter === deletingCategory.id) setCategoryFilter("all"); setDeletingCategory(null); setNotice(data.reassignedCount ? `已刪除分類，並重新整理 ${data.reassignedCount} 筆項目。` : "已刪除分類。"); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法刪除分類。"); } finally { setPending(false); } }
  const filteredItems = items.filter((item) => `${item.label} ${item.username} ${item.notes}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()) && (categoryFilter === "all" || (categoryFilter === "unclassified" ? !item.categoryId : item.categoryId === categoryFilter)));
  const categoryLabel = (categoryId: string | null) => categories.find((category) => category.id === categoryId)?.name ?? "未分類";
  if (!status) return <p className="lead">正在準備保管庫…</p>;
  if (!status.initialized) return <VaultGate creating error={error} onSubmit={initialize} pending={pending} />;
  if (!vaultKey) return <VaultGate creating={false} error={error} onSubmit={unlock} pending={pending} />;
  return <section className="vault-workspace">
    <section className="vault-status-panel"><span aria-hidden="true" className="vault-status-icon">⌑</span><div><strong>保管庫已解鎖</strong><p>所有敏感文字皆在送往伺服器前由瀏覽器加密。</p></div><button className="secondary-button compact" onClick={lock} type="button">立即鎖定</button></section>
    <div className="vault-section-heading"><div><p className="eyebrow">PRIVATE RECORDS</p><h2>保管項目</h2><p>{items.length ? `已安全載入 ${items.length} 個項目。` : "新增第一筆加密保管項目。"}</p></div><button className="button vault-add-button" onClick={() => { setError(null); setEditing(null); setItemDialogOpen(true); }} type="button">＋ 新增保管項目</button></div>
    {error && <p className="notice error" role="alert">{error}</p>}{notice && <p className="notice success" role="status">{notice}</p>}
    <div className="vault-toolbar"><input aria-label="搜尋保管項目" onChange={(event) => setQuery(event.target.value)} placeholder="搜尋名稱、帳號或備註…" value={query} /><span>{filteredItems.length} 筆</span><button className={selectionMode ? "secondary-button compact active" : "secondary-button compact"} onClick={() => selectionMode ? closeSelectionMode() : setSelectionMode(true)} type="button">{selectionMode ? "取消選取" : "整理"}</button></div>
    <section className="vault-categories" aria-label="保管項目分類" data-chip-overflow-container><div className="vault-category-heading"><strong>分類</strong><div data-chip-overflow-actions><button className="secondary-button compact" onClick={openManager} type="button">管理</button><button className="button compact" onClick={() => { setError(null); setCategoryAddOpen(true); }} type="button">＋ 新增</button></div></div><div className="vault-category-row"><ResponsiveChipOverflow activeId={categoryFilter === "all" || categoryFilter === "unclassified" ? null : categoryFilter} className="vault-filter-chips" items={categories} itemId={(category) => category.id} itemMeasureKey={(category) => `${category.name}|${category.itemCount}`} leading={<><button className={categoryFilter === "all" ? "active" : ""} onClick={() => setCategoryFilter("all")} type="button">全部</button><button className={categoryFilter === "unclassified" ? "active" : ""} onClick={() => setCategoryFilter("unclassified")} type="button">未分類</button></>} leadingCount={2} renderItem={(category) => <button className={categoryFilter === category.id ? "active" : ""} key={category.id} onClick={() => setCategoryFilter(category.id)} type="button">{category.name}{category.itemCount ? ` ${category.itemCount}` : ""}</button>} renderMore={(hasHiddenActive) => <button aria-expanded={categoryMoreOpen} className={hasHiddenActive ? "active" : ""} onClick={() => setCategoryMoreOpen((current) => !current)} type="button">更多</button>} rowClassName="vault-filter-chips-row" />{categoryMoreOpen && <div className="vault-more-categories">{categories.map((category) => <button className={categoryFilter === category.id ? "active" : ""} key={category.id} onClick={() => { setCategoryFilter(category.id); setCategoryMoreOpen(false); }} type="button">{category.name}{category.itemCount ? ` ${category.itemCount}` : ""}</button>)}</div>}</div></section>
    {selectionMode && <section className="vault-batch-toolbar"><label><input checked={filteredItems.length > 0 && filteredItems.every((item) => selectedItemIds.has(item.id))} onChange={(event) => setSelectedItemIds(event.target.checked ? new Set(filteredItems.map((item) => item.id)) : new Set())} type="checkbox" />全選目前清單</label><strong>已選 {selectedItemIds.size} 筆</strong><div><button className="secondary-button compact" disabled={!selectedItemIds.size || pending} onClick={() => { setBatchCategoryId("unclassified"); setBatchMoveOpen(true); }} type="button">移動分類</button><button className="delete-button compact" disabled={!selectedItemIds.size || pending} onClick={() => setBatchDeleteOpen(true)} type="button">刪除</button></div></section>}
    <div className="vault-grid">{filteredItems.map((item) => { const visible = visibleItemIds.has(item.id); const selected = selectedItemIds.has(item.id); return <article className={selected ? "vault-item selected" : "vault-item"} key={item.id}><header>{selectionMode ? <label className="vault-item-select"><input aria-label={`選取 ${item.label}`} checked={selected} onChange={() => toggleItemSelection(item.id)} type="checkbox" /><span>選取</span></label> : <span className="vault-kind-badge"><i aria-hidden="true">⌑</i>{categoryLabel(item.categoryId)}</span>}<div className="vault-item-menu"><button aria-expanded={menuItemId === item.id} aria-label={`開啟 ${item.label} 的操作選單`} className="vault-menu-trigger" onClick={() => setMenuItemId((current) => current === item.id ? null : item.id)} type="button">⋯</button>{menuItemId === item.id && <div className="vault-item-menu-popover"><button onClick={() => { setError(null); setEditing(item); setItemDialogOpen(true); }} type="button">編輯</button><button className="vault-menu-delete" disabled={pending} onClick={() => setDeleting(item)} type="button">刪除</button></div>}</div></header><div className="vault-item-content"><h3>{item.label}</h3>{item.username && <p className="vault-username">{item.username}</p>}<code aria-label={visible ? "敏感內容已顯示" : "敏感內容已遮蔽"}>{visible ? item.secret : maskedSecret(item.secret)}</code>{item.notes && <p className="vault-notes">{item.notes}</p>}</div><footer><button className="secondary-button compact" onClick={() => setVisibleItemIds((current) => { const next = new Set(current); if (next.has(item.id)) next.delete(item.id); else next.add(item.id); return next; })} type="button">{visible ? "隱藏" : "顯示"}</button><button className="secondary-button compact" onClick={() => void copySecret(item)} type="button">複製</button></footer></article>; })}</div>
    {!filteredItems.length && <section className="vault-empty"><strong>{items.length ? "找不到符合的保管項目" : "尚未建立加密項目"}</strong><p>{items.length ? "試著調整搜尋文字或分類。" : "按上方「新增保管項目」開始建立。"}</p></section>}
    <ModalDialog className="vault-item-dialog" onClose={closeItemDialog} open={itemDialogOpen} pending={pending} title={editing ? "編輯保管項目" : "新增保管項目"}><form className="vault-item-form" key={editing?.id ?? "new"} onSubmit={saveItem}><label>項目名稱<input defaultValue={editing?.label ?? ""} name="label" placeholder="例如 GitHub、主要銀行" required /></label><label>分類<select defaultValue={editing?.categoryId ?? ""} name="categoryId"><option value="">未分類</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>帳號／使用者名稱<input defaultValue={editing?.username ?? ""} name="username" placeholder="選填" /></label><label>密碼或敏感內容<textarea defaultValue={editing?.secret ?? ""} name="secret" placeholder="密碼、API Key、Recovery Code…" required rows={4} /></label><label>備註<textarea defaultValue={editing?.notes ?? ""} name="notes" placeholder="選填" rows={3} /></label><div className="dialog-actions"><button className="button" disabled={pending} type="submit">{pending ? "加密儲存中…" : (editing ? "重新加密並儲存" : "加密儲存")}</button><button className="secondary-button" disabled={pending} onClick={closeItemDialog} type="button">取消</button></div></form></ModalDialog>
    <ModalDialog onClose={() => { if (!pending) setCategoryAddOpen(false); }} open={categoryAddOpen} pending={pending} title="新增保管庫分類"><form className="vault-item-form" onSubmit={addCategory}><label>分類名稱<input autoFocus onChange={(event) => setCategoryName(event.target.value)} placeholder="例如：遊戲帳號、工作、信箱" required value={categoryName} /></label><div className="dialog-actions"><button className="button" disabled={pending} type="submit">{pending ? "新增中…" : "＋ 新增分類"}</button><button className="secondary-button" disabled={pending} onClick={() => setCategoryAddOpen(false)} type="button">取消</button></div></form></ModalDialog>
    <ModalDialog className="vault-category-manager-dialog" onClose={() => { if (!pending) setCategoryManagerOpen(false); }} open={categoryManagerOpen} pending={pending} title="管理保管庫分類"><p className="vault-manager-help">可修改名稱，並用上下按鈕調整顯示順序。刪除分類時，底下資料會先移到你選擇的分類或未分類。</p><div className="vault-category-manager-list">{categoryDraft.map((category, index) => <article key={category.id}><input aria-label={`分類名稱：${category.name}`} onChange={(event) => setCategoryDraft((current) => current.map((item) => item.id === category.id ? { ...item, name: event.target.value } : item))} value={category.name} /><span>{category.itemCount} 筆</span><div><button aria-label={`將 ${category.name} 往上移`} disabled={index === 0 || pending} onClick={() => moveCategory(category.id, -1)} type="button">↑</button><button aria-label={`將 ${category.name} 往下移`} disabled={index === categoryDraft.length - 1 || pending} onClick={() => moveCategory(category.id, 1)} type="button">↓</button><button aria-label={`刪除 ${category.name}`} className="vault-category-delete" disabled={pending} onClick={() => { setReassignCategoryId("unclassified"); setDeletingCategory(category); }} type="button">×</button></div></article>)}{!categoryDraft.length && <p className="vault-manager-help">尚未建立分類。</p>}</div><div className="dialog-actions"><button className="button" disabled={pending} onClick={() => void saveCategoryManager()} type="button">{pending ? "儲存中…" : "儲存整理"}</button><button className="secondary-button" disabled={pending} onClick={() => setCategoryManagerOpen(false)} type="button">關閉</button></div></ModalDialog>
    <ModalDialog onClose={() => { if (!pending) setDeletingCategory(null); }} open={Boolean(deletingCategory)} pending={pending} title="刪除保管庫分類"><div className="vault-category-delete-dialog"><p>「{deletingCategory?.name}」底下的 {deletingCategory?.itemCount ?? 0} 筆資料不會被刪除。請選擇要移到哪裡。</p><label>重新指派到<select onChange={(event) => setReassignCategoryId(event.target.value)} value={reassignCategoryId}><option value="unclassified">未分類</option>{categories.filter((category) => category.id !== deletingCategory?.id).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="dialog-actions"><button className="delete-button" disabled={pending} onClick={() => void removeCategory()} type="button">{pending ? "處理中…" : "刪除分類並重新指派"}</button><button className="secondary-button" disabled={pending} onClick={() => setDeletingCategory(null)} type="button">取消</button></div></div></ModalDialog>
    <ModalDialog onClose={() => { if (!pending) setBatchMoveOpen(false); }} open={batchMoveOpen} pending={pending} title="批量移動分類"><div className="vault-category-delete-dialog"><p>將 {selectedItemIds.size} 筆保管資料移到指定分類；敏感內容不會被解密或重新傳送。</p><label>移動到<select onChange={(event) => setBatchCategoryId(event.target.value)} value={batchCategoryId}><option value="unclassified">未分類</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="dialog-actions"><button className="button" disabled={pending} onClick={() => void runBatch("move")} type="button">{pending ? "移動中…" : "移動分類"}</button><button className="secondary-button" disabled={pending} onClick={() => setBatchMoveOpen(false)} type="button">取消</button></div></div></ModalDialog>
    <ConfirmDialog confirmLabel="刪除已選資料" description={`將永久刪除已選的 ${selectedItemIds.size} 筆保管資料，無法還原。`} error={error} onCancel={() => setBatchDeleteOpen(false)} onConfirm={() => { void runBatch("delete"); }} open={batchDeleteOpen} pending={pending} title="批量刪除保管資料？" />
    <ConfirmDialog description={`「${deleting?.label ?? ""}」將永久刪除，無法還原。`} error={error} onCancel={() => setDeleting(null)} onConfirm={() => { void remove(); }} open={Boolean(deleting)} pending={pending} title="刪除保管庫項目？" />
  </section>;
}
