"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";

type VaultStatus = { initialized: boolean; salt?: string; wrappedVaultKey?: string; wrappedKeyNonce?: string; kdfParameters?: { algorithm: "PBKDF2"; hash: "SHA-256"; iterations: number; keyLength: 256 } };
type CipherItem = { id: string; ciphertext: string; nonce: string; aad: { entryId: string; version: 1 } };
type PlainItem = { id: string; label: string; username: string; secret: string; notes: string };
const encoder = new TextEncoder(); const decoder = new TextDecoder(); const iterations = 600_000;
const toBase64 = (bytes: ArrayBuffer | Uint8Array) => { const data = new Uint8Array(bytes); let binary = ""; data.forEach((byte) => { binary += String.fromCharCode(byte); }); return btoa(binary); };
const fromBase64 = (value: string) => Uint8Array.from(atob(value), (char) => char.charCodeAt(0));
const asArrayBuffer = (bytes: Uint8Array) => bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
const randomBytes = (length: number) => crypto.getRandomValues(new Uint8Array(length));
async function deriveKey(password: string, salt: Uint8Array, count: number) { const material = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveKey"]); return crypto.subtle.deriveKey({ name: "PBKDF2", hash: "SHA-256", salt: asArrayBuffer(salt), iterations: count }, material, { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]); }

export function VaultWorkspace() {
  const [status, setStatus] = useState<VaultStatus | null>(null); const [vaultKey, setVaultKey] = useState<CryptoKey | null>(null); const [items, setItems] = useState<PlainItem[]>([]); const [visibleItemIds, setVisibleItemIds] = useState<Set<string>>(() => new Set()); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const activityTimer = useRef<number | null>(null);
  const lock = useCallback(() => { setVaultKey(null); setItems([]); setVisibleItemIds(new Set()); setError(null); }, []);
  const fetchStatus = useCallback(async () => { const response = await fetch("/api/vault", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法讀取保管庫。"); return data as VaultStatus; }, []);
  useEffect(() => { let cancelled = false; void fetchStatus().then((data) => { if (!cancelled) setStatus(data); }).catch((cause) => { if (!cancelled) setError(cause.message); }); return () => { cancelled = true; }; }, [fetchStatus]);
  useEffect(() => { if (!vaultKey) return; const reset = () => { if (activityTimer.current) window.clearTimeout(activityTimer.current); activityTimer.current = window.setTimeout(lock, 10 * 60 * 1000); }; reset(); window.addEventListener("pointerdown", reset); window.addEventListener("keydown", reset); return () => { if (activityTimer.current) window.clearTimeout(activityTimer.current); window.removeEventListener("pointerdown", reset); window.removeEventListener("keydown", reset); }; }, [vaultKey, lock]);
  async function decryptItems(key: CryptoKey) { const response = await fetch("/api/vault/items", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法讀取加密項目。"); const decrypted = await Promise.all((data.items as CipherItem[]).map(async (item) => { const plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64(item.nonce), additionalData: encoder.encode(JSON.stringify(item.aad)) }, key, fromBase64(item.ciphertext)); return { id: item.id, ...JSON.parse(decoder.decode(plain)) } as PlainItem; })); setItems(decrypted); }
  async function initialize(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get("password") ?? ""); const confirmation = String(form.get("confirmation") ?? ""); if (password.length < 12 || password !== confirmation) { setError("請設定至少 12 字元且兩次相同的 Vault 密碼。"); return; } setPending(true); setError(null); try { const salt = randomBytes(16); const wrappingNonce = randomBytes(12); const wrappingKey = await deriveKey(password, salt, iterations); const generated = await crypto.subtle.generateKey({ name: "AES-GCM", length: 256 }, true, ["encrypt", "decrypt"]); const rawVaultKey = await crypto.subtle.exportKey("raw", generated); const wrappedVaultKey = await crypto.subtle.encrypt({ name: "AES-GCM", iv: wrappingNonce, additionalData: encoder.encode("personal-vault-key:v1") }, wrappingKey, rawVaultKey); const response = await fetch("/api/vault", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ salt: toBase64(salt), wrappedVaultKey: toBase64(wrappedVaultKey), wrappedKeyNonce: toBase64(wrappingNonce), kdfParameters: { algorithm: "PBKDF2", hash: "SHA-256", iterations, keyLength: 256 } }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法建立保管庫。"); setVaultKey(await crypto.subtle.importKey("raw", rawVaultKey, { name: "AES-GCM" }, false, ["encrypt", "decrypt"])); setStatus(await fetchStatus()); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法建立保管庫。"); } finally { setPending(false); } }
  async function unlock(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!status?.initialized || !status.salt || !status.wrappedVaultKey || !status.wrappedKeyNonce || !status.kdfParameters) return; const password = String(new FormData(event.currentTarget).get("password") ?? ""); setPending(true); setError(null); try { const wrappingKey = await deriveKey(password, fromBase64(status.salt), status.kdfParameters.iterations); const raw = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64(status.wrappedKeyNonce), additionalData: encoder.encode("personal-vault-key:v1") }, wrappingKey, fromBase64(status.wrappedVaultKey)); const key = await crypto.subtle.importKey("raw", raw, { name: "AES-GCM" }, false, ["encrypt", "decrypt"]); await decryptItems(key); setVaultKey(key); } catch { setError("Vault 密碼錯誤，或加密資料無法驗證。"); } finally { setPending(false); } }
  async function addItem(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!vaultKey) return; const form = new FormData(event.currentTarget); const id = crypto.randomUUID(); const aad = { entryId: id, version: 1 as const }; const value = { label: String(form.get("label") ?? ""), username: String(form.get("username") ?? ""), secret: String(form.get("secret") ?? ""), notes: String(form.get("notes") ?? "") }; if (!value.label || !value.secret) { setError("請填寫項目名稱與敏感內容。"); return; } setPending(true); setError(null); try { const nonce = randomBytes(12); const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv: nonce, additionalData: encoder.encode(JSON.stringify(aad)) }, vaultKey, encoder.encode(JSON.stringify(value))); const response = await fetch("/api/vault/items", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, ciphertext: toBase64(ciphertext), nonce: toBase64(nonce), aad }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "無法儲存項目。"); event.currentTarget.reset(); await decryptItems(vaultKey); } catch (cause) { setError(cause instanceof Error ? cause.message : "無法儲存項目。"); } finally { setPending(false); } }
  async function remove(id: string) { if (!vaultKey || !window.confirm("確定要永久刪除這個 Vault 項目嗎？")) return; setPending(true); const response = await fetch("/api/vault/items", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); setPending(false); if (!response.ok) { setError("無法刪除項目。"); return; } await decryptItems(vaultKey); }
  if (!status) return <p className="lead">正在準備保管庫…</p>;
  if (!status.initialized) return <section className="vault-panel narrow-card"><p className="eyebrow">ZERO-KNOWLEDGE VAULT</p><h2>建立 Vault 密碼</h2><p>此密碼只在此裝置的瀏覽器中使用來解鎖資料；我們無法替你重設，請妥善保管。</p>{error && <p className="notice error" role="alert">{error}</p>}<form className="form" onSubmit={initialize}><div className="field"><label>Vault 密碼</label><input name="password" required type="password" autoComplete="new-password" /></div><div className="field"><label>再次輸入 Vault 密碼</label><input name="confirmation" required type="password" autoComplete="new-password" /></div><button className="button" disabled={pending} type="submit">{pending ? "建立中…" : "建立加密保管庫"}</button></form></section>;
  if (!vaultKey) return <section className="vault-panel narrow-card"><p className="eyebrow">ZERO-KNOWLEDGE VAULT</p><h2>解鎖保管庫</h2><p>金鑰只會保存在此頁面的記憶體中，閒置 10 分鐘會自動鎖定。</p>{error && <p className="notice error" role="alert">{error}</p>}<form className="form" onSubmit={unlock}><div className="field"><label>Vault 密碼</label><input name="password" required type="password" autoComplete="current-password" /></div><button className="button" disabled={pending} type="submit">{pending ? "解鎖中…" : "解鎖 Vault"}</button></form></section>;
  return <section className="vault-workspace"><div className="vault-heading"><div><p className="eyebrow">ZERO-KNOWLEDGE VAULT</p><h2>已解鎖</h2><p>所有敏感文字在送往伺服器前已於瀏覽器加密。</p></div><button className="button secondary compact" onClick={lock} type="button">立即鎖定</button></div>{error && <p className="notice error" role="alert">{error}</p>}<form className="vault-form" onSubmit={addItem}><input aria-label="項目名稱" name="label" placeholder="項目名稱，例如 GitHub" required /><input aria-label="帳號或使用者名稱" name="username" placeholder="帳號／使用者名稱（選填）" /><textarea aria-label="密碼或敏感內容" name="secret" placeholder="密碼、API Key、Recovery Code…" required rows={3} /><textarea aria-label="備註" name="notes" placeholder="備註（選填）" rows={2} /><button className="button" disabled={pending} type="submit">{pending ? "加密儲存中…" : "加密儲存項目"}</button></form><div className="vault-list">{items.map((item) => { const visible = visibleItemIds.has(item.id); return <article className="vault-item" key={item.id}><div><h3>{item.label}</h3>{item.username && <p>{item.username}</p>}<code>{visible ? item.secret : "•".repeat(Math.min(Math.max(item.secret.length, 8), 24))}</code><button className="vault-reveal" onClick={() => setVisibleItemIds((current) => { const next = new Set(current); if (next.has(item.id)) next.delete(item.id); else next.add(item.id); return next; })} type="button">{visible ? "隱藏" : "顯示"}</button>{item.notes && <p>{item.notes}</p>}</div><button className="delete-button" disabled={pending} onClick={() => void remove(item.id)} type="button">刪除</button></article>; })}{items.length === 0 && <p className="lead">尚未建立加密項目。</p>}</div></section>;
}
