-- Japanese → Traditional Chinese meanings must come from a sense-aware
-- dictionary source.  Do not treat a machine-translated English gloss as
-- canonical vocabulary content.

alter table public.system_vocabulary
  add column if not exists meanings_zh_tw jsonb not null default '[]'::jsonb;

comment on column public.system_vocabulary.meanings_zh_tw is
  'Ordered Traditional Chinese meanings by dictionary sense. Canonical Japanese translations are source-verified, not machine generated.';

insert into public.dictionary_sources (slug, name, source_url, license, attribution, source_version)
values (
  'tomoshi-jmdict-zhtw',
  'Tomoshi JMdict Traditional Chinese definitions',
  'https://github.com/tomoshi-app/tomoshi-dict-data',
  'CC BY-SA 4.0',
  'EDRDG JMdict / Tomoshi dictionary data. Traditional Chinese definitions are sourced from Tomoshi data; modifications are identified in the Personal Vault import pipeline.',
  'v2026-08-12'
)
on conflict (slug) do update set
  name = excluded.name,
  source_url = excluded.source_url,
  license = excluded.license,
  attribution = excluded.attribution,
  source_version = excluded.source_version,
  updated_at = now();

-- Existing entries were generated by the former public machine-translation
-- fallback. Clear only that unverified Japanese cache so a stale incorrect
-- string can never be preferred over the verified source imported next.
update public.dictionary_translations
set
  primary_meaning = null,
  meanings_json = '[]'::jsonb,
  source = 'retired-machine-translation',
  verified = false,
  updated_at = now()
where source_language = 'ja'
  and verified = false
  and source in ('translation-fallback', 'translation-cache-cleanup');

-- The following RPC is server-only. It lets the local trusted importer update
-- all three linked tables in batches without exposing translation writes to
-- browsers or issuing thousands of individual requests.
create or replace function public.apply_verified_japanese_translation_batch(p_updates jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected_count integer;
begin
  if jsonb_typeof(p_updates) <> 'array' then
    raise exception 'p_updates must be a JSON array';
  end if;

  with patch as (
    select *
    from jsonb_to_recordset(p_updates) as value(
      dictionary_entry_id uuid,
      normalized_word text,
      primary_meaning text,
      meanings_json jsonb,
      senses jsonb,
      english_definition text,
      part_of_speech text
    )
  ), translated as (
    insert into public.dictionary_translations (
      source_language, normalized_word, target_language, primary_meaning,
      meanings_json, source, verified, updated_at
    )
    select
      'ja', patch.normalized_word, 'zh-TW', patch.primary_meaning,
      patch.meanings_json, 'tomoshi-jmdict-zhtw', true, now()
    from patch
    on conflict (source_language, normalized_word, target_language) do update set
      primary_meaning = excluded.primary_meaning,
      meanings_json = excluded.meanings_json,
      source = excluded.source,
      verified = true,
      updated_at = now()
    returning normalized_word
  ), dictionary_updated as (
    update public.dictionary_entries entry
    set
      primary_translation = patch.primary_meaning,
      senses = patch.senses,
      english_definition = patch.english_definition,
      part_of_speech = patch.part_of_speech,
      source_metadata = coalesce(entry.source_metadata, '{}'::jsonb) || jsonb_build_object(
        'traditionalChineseTranslationSource', 'tomoshi-jmdict-zhtw',
        'traditionalChineseVerified', true,
        'traditionalChineseUpdatedAt', now()
      ),
      updated_at = now()
    from patch
    where entry.id = patch.dictionary_entry_id
    returning entry.id
  ), catalog_updated as (
    update public.system_vocabulary catalog
    set
      meaning_zh_tw = patch.primary_meaning,
      meanings_zh_tw = patch.meanings_json,
      english_definition = patch.english_definition,
      part_of_speech = patch.part_of_speech,
      updated_at = now()
    from patch
    where catalog.dictionary_entry_id = patch.dictionary_entry_id
      and catalog.language = 'ja'
    returning catalog.id
  )
  select count(*) into affected_count from catalog_updated;

  return affected_count;
end;
$$;

revoke all on function public.apply_verified_japanese_translation_batch(jsonb) from public, anon, authenticated;
grant execute on function public.apply_verified_japanese_translation_batch(jsonb) to service_role;
