-- Application-side controls around Supabase Auth email OTP delivery.
-- Supabase Auth owns and hashes the actual OTP. These tables only retain
-- flow/rate-limit metadata and one-time password-reset authorizations.

create table if not exists public.auth_verification_flows (
  id uuid primary key default gen_random_uuid(),
  email citext not null,
  purpose text not null check (purpose in ('email_verification', 'password_reset')),
  expires_at timestamptz not null,
  last_sent_at timestamptz not null,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  consumed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (email, purpose)
);

create table if not exists public.auth_otp_send_events (
  id bigint generated by default as identity primary key,
  flow_id uuid references public.auth_verification_flows(id) on delete cascade,
  email_hash text not null,
  ip_hash text not null,
  purpose text not null check (purpose in ('email_verification', 'password_reset')),
  created_at timestamptz not null default now()
);

create table if not exists public.password_reset_authorizations (
  id uuid primary key default gen_random_uuid(),
  flow_id uuid not null references public.auth_verification_flows(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists auth_verification_flows_expiry_idx
  on public.auth_verification_flows (expires_at);
create index if not exists auth_otp_send_events_email_idx
  on public.auth_otp_send_events (email_hash, purpose, created_at desc);
create index if not exists auth_otp_send_events_ip_idx
  on public.auth_otp_send_events (ip_hash, created_at desc);
create index if not exists password_reset_authorizations_user_idx
  on public.password_reset_authorizations (user_id, created_at desc);

drop trigger if exists vault_app_auth_verification_flows_updated_at
  on public.auth_verification_flows;
create trigger vault_app_auth_verification_flows_updated_at
before update on public.auth_verification_flows
for each row execute procedure public.vault_app_set_updated_at();

alter table public.auth_verification_flows enable row level security;
alter table public.auth_otp_send_events enable row level security;
alter table public.password_reset_authorizations enable row level security;

revoke all on table public.auth_verification_flows from anon, authenticated;
revoke all on table public.auth_otp_send_events from anon, authenticated;
revoke all on table public.password_reset_authorizations from anon, authenticated;
grant select, insert, update, delete on table public.auth_verification_flows to service_role;
grant select, insert, update, delete on table public.auth_otp_send_events to service_role;
grant select, insert, update, delete on table public.password_reset_authorizations to service_role;
grant usage, select on sequence public.auth_otp_send_events_id_seq to service_role;

-- Atomically reserve one delivery before contacting the email provider. The
-- advisory locks prevent concurrent requests from passing the same limit.
create or replace function public.reserve_auth_otp_send(
  requested_email_hash text,
  requested_ip_hash text,
  requested_purpose text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  latest_sent_at timestamptz;
  oldest_sent_at timestamptz;
  email_send_count integer;
  ip_send_count integer;
  reserved_event_id bigint;
  retry_after integer;
begin
  if requested_purpose not in ('email_verification', 'password_reset') then
    raise exception 'Invalid OTP purpose';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('otp-email:' || requested_email_hash, 0));
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('otp-ip:' || requested_ip_hash, 0));

  select max(events.created_at), min(events.created_at), count(*)::integer
    into latest_sent_at, oldest_sent_at, email_send_count
  from public.auth_otp_send_events as events
  where events.email_hash = requested_email_hash
    and events.purpose = requested_purpose
    and events.created_at >= now() - interval '10 minutes';

  if latest_sent_at is not null and latest_sent_at > now() - interval '60 seconds' then
    retry_after := greatest(1, ceil(extract(epoch from (latest_sent_at + interval '60 seconds' - now())))::integer);
    return jsonb_build_object('allowed', false, 'retryAfter', retry_after);
  end if;

  if email_send_count >= 3 then
    retry_after := greatest(1, ceil(extract(epoch from (oldest_sent_at + interval '10 minutes' - now())))::integer);
    return jsonb_build_object('allowed', false, 'retryAfter', retry_after);
  end if;

  select count(*)::integer into ip_send_count
  from public.auth_otp_send_events as events
  where events.ip_hash = requested_ip_hash
    and events.created_at >= now() - interval '10 minutes';

  if ip_send_count >= 10 then
    return jsonb_build_object('allowed', false, 'retryAfter', 60);
  end if;

  insert into public.auth_otp_send_events (email_hash, ip_hash, purpose)
  values (requested_email_hash, requested_ip_hash, requested_purpose)
  returning id into reserved_event_id;

  return jsonb_build_object('allowed', true, 'eventId', reserved_event_id);
end;
$$;

revoke all on function public.reserve_auth_otp_send(text, text, text) from public;
grant execute on function public.reserve_auth_otp_send(text, text, text) to service_role;

-- The signup API uses this server-only lookup to reuse an existing pending
-- Auth user instead of creating duplicate registrations.
create or replace function public.lookup_auth_email_status(requested_email text)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (
      select jsonb_build_object(
        'userId', users.id,
        'confirmed', users.email_confirmed_at is not null
      )
      from auth.users as users
      where lower(users.email) = lower(btrim(requested_email))
        and users.deleted_at is null
      limit 1
    ),
    jsonb_build_object('userId', null, 'confirmed', false)
  );
$$;

revoke all on function public.lookup_auth_email_status(text) from public;
grant execute on function public.lookup_auth_email_status(text) to service_role;

notify pgrst, 'reload schema';
